### ISSUE TITLE
change prefix of indicator fields  from `z_crt` to `z_ind`

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#18]

**Comment by emjay0921** [comment]
I can't change the prefix x_ to z_. Odoo is not allowing me to change the x_ prefix.

**Comment by jeremi** [comment]
@emjay0921 Don't forget to update the demos

**Comment by emjay0921** [comment]
@jeremi Updates on demos: PR https://github.com/openspp-project/openspp-demo/pull/12
