### ISSUE TITLE
Associate a company and contacts to each service point.

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#245]
1. Add a res_partner company association to the Service Point model.
2. Allow contacts to be associated with the res_partner company.
3. Contacts can be users of a third-party POS application for entitlement distribution.
4. Utilize the parent concept of res_partner for implementing contacts.
5. Make it optional (settings) to have contacts to be Odoo users, that have no access except a group service_point_users.
6. Improve the existing Service Point model by adding new fields and methods.

**Comment by jeremi** [comment]
@gonzalesedwin1123 do you think it is a good idea? 
If so, @emjay0921  will implement it.

**Comment by gonzalesedwin1123** [comment]
@jeremi, I think this is a very good.

**Comment by reichie020212** [comment]
June 29, 2023 

- Read, analyze, research the requirements of this ticket
- Will discuss with @gonzalesedwin1123 about this ticket and answer some of my questions tomorrow.

**Comment by kneckinator** [comment]
@jeremi is this to facilitate the association of "POS Terminal Users" with a service point and to also be able to interact with a company for retailer settlements (Odoo billing/invoicing)?

**Comment by gonzalesedwin1123** [comment]
@jeremi please check if the following are correct:

`1. Add a res_partner company association to the Service Point model.`
- Create a company(res.company) for every service point (spp.service.point). 

`4. Utilize the parent concept of res_partner for implementing contacts.`
- Contacts refers to the registrants.
- Parent concept of res_partner will be used for the group and individual relationship.

**Comment by dasunhegoda** [comment]
We will need @jeremi's help clarifying points 4,6. The rest @reichie020212 can continue.

**Comment by jeremi** [comment]
1. No a res_partner that has the `is_company` set to true. Like in Odoo CRM. Not a res_company.
4. No Contact of a service point. Parent concept = odoo parent concept: 
6. Not sure what I wanted to add, so forget about it :)


![Image](https://github.com/OpenSPP/openspp-registry/assets/9537/fd309450-3ea4-4cb4-9eeb-fccee8ac12a0)

**Comment by dasunhegoda** [comment]
@reichie020212 Could you look into this?

**Comment by reichie020212** [comment]
@dasunhegoda @jeremi , In my code, I used the res_partner with is_company=True as company and already used the parent concept of res_partner

**Comment by adriancris** [comment]
QA Passed
Working as expected

**Comment by adriancris** [comment]
@reichie020212 
A service point user still shows up in the API even when the company associated to it has already been deleted.

**Comment by jeremi** [comment]
I think we need to configure the cascading @reichie020212

**Comment by reichie020212** [comment]
@jeremi I already fixed the last issue @adriancris reported and what I did is I reconfigured the many2many relationship table I used for service_point and res_partner and then added related field to res_users to be used as domain in the API.

**Comment by adriancris** [comment]
QA Passed. 
Working as expected.
Testcases executed: TSOS-150 and TSOS-151
