### ISSUE TITLE
Improve odoo import for registrant

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#247]
A significant modification in the system will be the addition of a new, unique identifier field `registrant_id` to the `res.partner` model. This identifier will be either manually imported or automatically generated, and it will not follow a sequential pattern. Instead, it will be simple and not easily guessable. This `registrant_id` will also be used as the external ID for the record if feasible.

#### 2.1 Addition of `registrant_id` field:
A new field, `registrant_id`, will be added to the `res.partner` model. This ID will be unique for each instance, and it will be indexed for efficient search operations. This `registrant_id` will also serve as the external ID of the record.

#### 2.2 Differentiation between Group and Individual:
The system will differentiate between group and individual registrants. The `registrant_id` will have a prefix of 'GRP_' for groups and 'IND_' for individuals. The differentiation will be based on an existing attribute or method in the `res.partner` model.

#### 2.3 Generation of `registrant_id`:
If `registrant_id` is not manually imported, the system will automatically generate it. This generation process will be simple and involve concatenating the respective prefix ('GRP_' or 'IND_') with a unique, non-sequential identifier. 

```python
    def _generate_unique_id(self):
        length = 8  # Adjust the desired length of the unique identifier
        
        # Define the characters allowed in the unique identifier
        characters = string.digits + string.ascii_uppercase
        excluded_characters = ['0', 'O', '1', 'I']  # Exclude characters that can be confused
        
        # Filter the characters to exclude
        allowed_characters = [c for c in characters if c not in excluded_characters]
        
        # Generate the unique identifier by randomly selecting characters
        unique_id = ''.join(random.choice(allowed_characters) for _ in range(length))
        
        return unique_id
```

#### 2.4 Validation of `registrant_id`:
The system will validate the uniqueness of `registrant_id` across all instances of `res.partner`. If any duplicate `registrant_id` is found, the system will raise an exception, alerting the user of the duplication issue.

### 3. Performance Considerations
To ensure optimal operation and performance, the system will:

- Index the `registrant_id` field in the database to speed up search operations.
- Be mindful of excessive usage of the method for checking the uniqueness of `registrant_id`, as it could affect system performance due to the involved database search operations.

With this updated specification, the OpenSPP system should efficiently manage unique identification of registrants, either as groups or individuals, and use the `registrant_id` as the external ID of the record, provided it's feasible. The precise method for generating the unique identifier part of `registrant_id` is subject to further discussion and definition.

### 4 configure the importer
Configure the importer to match on registrant_id using https://github.com/OpenSPP/openspp-registry/pull/237

**Comment by gonzalesedwin1123** [comment]
@nhatnm0612 Have you addressed "4 configure the importer"?

**Comment by gonzalesedwin1123** [comment]
@jeremi @nhatnm0612 @dasunhegoda  may I propose to move this to openspp-base repo and change the module folder name to spp_registry so that all OpenSPP customizations for the registry will be done in this module.

**Comment by nhatnm0612** [comment]
@gonzalesedwin1123 I changed some code so it can be used for import, also setup things based on #237 , or I need to create data for this?

**Comment by gonzalesedwin1123** [comment]
Yes @nhatnm0612 , you need to create the data.

**Comment by adriancris** [comment]
@nhatnm0612 I manually provided registrant ID but it is not correctly displayed when Individual is imported. It is automatically created even when I provided the registrant ID

**Comment by nhatnm0612** [comment]
> @nhatnm0612 I manually provided registrant ID but it is not correctly displayed when Individual is imported. It is automatically created even when I provided the registrant ID

@adriancris @gonzalesedwin1123 @dasunhegoda @jeremi according to this issue raised by Adrian:

The normal Odoo import behavior will create new registrant with import document prepared registrant_id. But in spp_import_match, @emjay0921 has to work around and remove the data got from document to ensure the uniqueness of import key ([the code is here](https://github.com/OpenSPP/openspp-base/blob/1e613ab3a6243d08661554b4acfefb168a1aaf7c/spp_import_match/models/base.py#L42)). I chatted with him this afternoon, and he noted down the important of this removal.

So, it's either we do not use Odoo import feature to create records with this data, or we need a new flow to override this match key removal & let the users have their responsibility to keep the uniqueness for the table column.

**Comment by adriancris** [comment]
@nhatnm0612 
when I try to edit an imported individual, their given and family name disappears.
according to @celinenilla regardless if the name is conventional or not, the edit should behave as the same. kindly have a look at it. thank you.

https://github.com/OpenSPP/openspp-registry/assets/138551361/a4ab4f7c-67e0-48e2-8d18-30061b77e245

**Comment by adriancris** [comment]
@nhatnm0612 
Individual and Group with Registrant IDs like the ones below are still accepted. It is valid when importing an Individual or Group. Kindly check. Thank you.

IND_a9b8c7d6
GRP_g9h4y3s2

**Comment by adriancris** [comment]
Individual
Manually Provided Registrant IDs
[TSACF-1] Import an Individual with Unique Registrant ID
[TSACF-2] Import an Individual with Duplicate Registrant ID - Allow Overwrite
[TSACF-50] Import an Individual with Duplicate Registrant ID - Prevent Overwrite
[TSACF-3] Import an Individual with Incorrect Registrant ID Format
[TSACF-5] Export Individual/s
[TSACF-6] Search an Individual using Registrant ID

Automatically Generated Registrant IDs
[TSACF-8] Import an Individual with No Registrant ID
[TSACF-9] Import at least two Individuals with No Registrant IDs
*
*
*
Group
Manually Provided Registrant IDs
[TSACF-10] Import a Group with Unique Registrant ID
[TSACF-11] Import a Group with Duplicate Registrant ID - Allow Overwrite
[TSACF-51] Import a Group with Duplicate Registrant ID - Prevent Overwrite
[TSACF-12] Import a Group with Incorrect Registrant ID Format
[TSACF-14] Export Group/s
[TSACF-15] Search a Group using Registrant ID

Automatically Generated Registrant IDs
[TSACF-17] Import a Group with No Registrant ID
[TSACF-18] Import at least two Groups with No Registrant IDs

**Comment by adriancris** [comment]
@nhatnm0612 
kindly have the registrant ID displayed to all as per @celinenilla

**Comment by adriancris** [comment]
Setting the status back to In progress as @nhatnm0612 is fixing bugs

**Comment by adriancris** [comment]
Test cases:
OpenSPP > OpenSPP registry > Import > Unique ID
