### ISSUE TITLE
Extend ID Document to support top-up card

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#249]
**For Modifications:**
- Change the column label of **Top-Up** "**Card UID**" to "**Card Serial Number**"

How to Use:
- Can be in Individuals or Groups
- Select one recoard and go to the IDs bab
- On Registrant Form, add and ID and select Top-up Card as ID Type
- Add the UID Card Number.

**Comment by kneckinator** [comment]
The top-up card document type will need a new field, `card_uid` (or shorter `uid`). The field should be a 10-character string – or if available as a data type – 10 bytes.

10 bytes allow for storing the UIDs of EV1, EV2 and EV3-type cards.

**Comment by emjay0921** [comment]
Done @kneckinator

**Comment by gonzalesedwin1123** [comment]
@emjay0921 please check the required modifications in the description.
