### ISSUE TITLE
Generate the res.partner name field value based on the name sub-fields

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#253]
This ticket is applicable when using Odoo import. 

The res.partner name field must be generated based on imports of values to its sub-fields:

- given name
- last name
- other name

Currently, the name field is generated when its sub-fields are populated in the Registry UI.

**Comment by adriancris** [comment]
QA Passed
Working as expected

**Comment by gonzalesedwin1123** [comment]
PR needs to be merged to 15.1.1
