### ISSUE TITLE
create unique id on areas & service points for integrate with OpenFN

### ISSUE THREAD

**Issue by nhatnm0612** [openspp-project/openspp-registry#273]
following #247 , but on service point & area

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test cases executed: 
TSOS-186
TSOS-187

**Comment by adriancris** [comment]
tested and approved without comments

**Comment by anthonymarkQA** [comment]
ODOO 17 version
ACF DEV

FIndings: Returned to DEV
Apply unique ID to service point - pass
![image](https://github.com/user-attachments/assets/6ce426c3-636c-4246-ba13-c2456a36daef)


Apply unique ID to Area - returned to dev, the placement is off and it does not have a label
![image](https://github.com/user-attachments/assets/7ce34271-ca30-4667-9b0e-69b5af84c7aa)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Unique ID in service point
![image](https://github.com/user-attachments/assets/53b9b97c-d013-4fc0-b08c-9a255f7e3298)



Unique ID in area
![image](https://github.com/user-attachments/assets/58067dae-f87a-4ba9-861d-d11111aca0b5)
