### ISSUE TITLE
Implement REST API for the registry

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#28]
- [ ] Define fine access right for each method: 
  - [ ] GET
  - [ ] POST
  - [ ] PUT

**Comment by gonzalesedwin1123** [comment]
Completed the createGroup function.

Todo: Fix error in "return GroupInfoOut.from_orm(partner)" when the "members" variable is set:
`class GroupInfoOut(RegistrantInfoOut):`
`    is_group = True`
`    # members: List[GroupMembersInfoOut] = pydantic.Field(`
`    #    ..., alias="group_membership_ids"`
`    # )`
`    kind: str = pydantic.Field(..., alias="kind_as_str")`

**Comment by gonzalesedwin1123** [comment]
The error was fixed with https://github.com/OpenG2P/openg2p-registry/commit/5ca09e21e5e75f010335d7751515931df1fb8d85
