### ISSUE TITLE
Fix the bug when entitlements are generated and cycles are created

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#291]
This error appears when entitlements are generated and cycles are created:

> RPC_ERROR
> 
> Odoo Server Error
> Traceback (most recent call last):
>   File "/opt/odoo/custom/src/odoo/odoo/api.py", line 886, in get
>     return field_cache[record._ids[0]]
> KeyError: 496
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1061, in __get__
>     value = env.cache.get(record, self)
>   File "/opt/odoo/custom/src/odoo/odoo/api.py", line 889, in get
>     raise CacheMiss(record, field)
> odoo.exceptions.CacheMiss: 'res.partner(496,).z_ind_grp_pmt_score'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
>     result = request.dispatch()
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 687, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 916, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 535, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/auto/addons/web/controllers/main.py", line 1346, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/auto/addons/web/controllers/main.py", line 1334, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/custom/src/odoo/odoo/api.py", line 465, in call_kw
>     model.flush()
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5661, in flush
>     process(self.env[model_name], id_vals)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5652, in process
>     recs._write(vals)
>   File "/opt/odoo/auto/addons/spp_audit_log/tools/decorator.py", line 54, in audit_write
>     old_values = self.sudo().read(load="_classic_write")
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3227, in read
>     return self._read_format(fnames=fields, load=load)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3247, in _read_format
>     vals[name] = convert(record[name], record, use_name_get)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5902, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1110, in __get__
>     self.compute_value(recs)
>   File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1269, in compute_value
>     records._compute_field_value(self)
>   File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 411, in _compute_field_value
>     return super()._compute_field_value(field)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4264, in _compute_field_value
>     getattr(self, field.compute)()
>   File "/opt/odoo/auto/addons/spp_pmt/models/pmt.py", line 66, in _compute_pmt_score
>     areas = field.area_ids.filtered(lambda a: a.name.id == hh_area.id)
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5503, in filtered
>     return self.browse([rec.id for rec in self if func(rec)])
>   File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5503, in <listcomp>
>     return self.browse([rec.id for rec in self if func(rec)])
>   File "/opt/odoo/auto/addons/spp_pmt/models/pmt.py", line 66, in <lambda>
>     areas = field.area_ids.filtered(lambda a: a.name.id == hh_area.id)
>   File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 4069, in __get__
>     raise ValueError("Expected singleton: %s" % record)
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 643, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/custom/src/odoo/odoo/http.py", line 301, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> ValueError: Expected singleton: spp.area(11, 10)

-This only appears when the user chooses YES in "Would you like to import the matching registrants to this program?"

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
Performed Regression Testing using: 

- Default, SQL, and Tag Eligibility Criteria
- Cash and In-kind Entitlements
- Yes / No in confirmation modal
- Created cycle, prepare and entitlements
