### ISSUE TITLE
Downgrade base_geoengine Module from Odoo 16.0 to 15.0

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#302]
The purpose of this ticket is to investigate and implement the downgrade of the base_geoengine module from its current version compatible with Odoo 16.0 to make it compatible with Odoo 15.0. The module will require PostGIS for geospatial capabilities. We will replace PostgreSQL with PostGIS. A drop-in Docker replacement is available and should be utilized.

The task is to estimate the amount of work required and proceed upon confirmation.

THe code:
 https://github.com/OCA/geospatial/tree/16.0/base_geoengine 

A demo is running here: [http://oca-geospatial-16-0-9c924edac445.runboat.odoo-community.org/web#action=91&model=geoengine.demo.automatic.retailing.machine&view_type=geoengine&cids=1&menu_id=7](http://oca-geospatial-16-0-9c924edac445.runboat.odoo-community.org/web#action=91&model=geoengine.demo.automatic.retailing.machine&view_type=geoengine&cids=1&menu_id=76)

**Comment by jeremi** [comment]
To install postgis: https://postgis.net/documentation/getting_started/
