### ISSUE TITLE
Develop a new module to replace the OCA DMS in the CR module

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#307]
- [ ] Develop a module for managing CR document attachments as a replacement to the OCA-DMS module.

description:
check DMS module
directory
view attachment
download attachment
view attachment via change request
able to delete as admin

**Comment by anthonymarkQA** [comment]
ACF DEV

Findings: Returned to DEV

DMS module visible and accessible - pass
directory to list all attachments within CR's -pass
view attachment - fail. no button to view attachment
download attachment - pass
view attachment via change request - fail, no button to view attachment
able to delete attachment friom directory list as  admin - pass

**Comment by gonzalesedwin1123** [comment]
@dasunhegoda @anthonymarkQA Can we have the "View attachment" in a new ticket since this is part of the javascript viewer that I am working on.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

remaining issues will be considered as improvement and will be separated into a ticket
DMS module visible and accessible - pass
directory to list all attachments within CR's -pass
download attachment - pass
able to delete attachment from directory list as admin - pass
