### ISSUE TITLE
Development of the "spp-cluster" Module for OpenSPP

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#338]
**Description:**

The objective of this ticket is to design and implement a separate module, named `spp-cluster`, within the OpenSPP ecosystem. This module will introduce and manage the concept of "Cluster," a new entity that represents a higher-level aggregation of groups or individuals. This modular approach ensures that the cluster functionality can be developed, deployed, and maintained independently, promoting modularity and ease of integration with the broader OpenSPP platform.

**Key Features of the `spp-cluster` Module:**

1. **Flexible Membership Configuration:** Each type of Cluster can be configured to determine its openness to individual and/or group memberships. This feature allows for tailored membership policies, accommodating the specific requirements of different Cluster types, such as cooperatives, educational institutions, etc.

2. **Customizable Relationship Types:** The module will allow for specifying the types of relationships supported within a Cluster. This capability enables the definition of various roles and connections between members, reflecting the real-world dynamics of the represented entities.

3. **Integration with Programs:** The `spp-cluster` module will introduce functionality to specify which types of Clusters are allowed within particular programs. This feature ensures that program administrators can control and customize the participation of different Cluster types in accordance with program objectives and requirements.

**Implementation Details:**

- **Module Structure:** Develop the `spp-cluster` as a standalone module within the OpenSPP architecture, ensuring it can be easily integrated into the existing system without requiring extensive modifications to the core platform.
  
- **Model Enhancements:** Extend the `res.partner` model within this module to incorporate fields and logic specific to Cluster management, including membership type configuration (individuals/groups) and supported relationship types.
  
- **UI Development:** Create another UI like to groups one.

**Expected Outcome:**

The successful development of the `spp-cluster` module will significantly enhance the OpenSPP platform's organizational capabilities, allowing for more nuanced and flexible grouping of beneficiaries. By enabling specific configurations for different types of Clusters and integrating these entities into program management workflows, OpenSPP will offer a more adaptable and powerful tool for managing social protection programs.

**Priority:** High

**Comment by jeremi** [comment]
see also #338 for the cluster type definition

**Comment by gonzalesedwin1123** [comment]
OK @jeremi , I'll work on this

**Comment by jeremi** [comment]
replaced by #339
