### ISSUE TITLE
Add a Manual Eligibility Manager

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#341]
Add a manual eligibility manager that automatically accepts everyone added to the program.

1. Create Program with Manual Eligibility as the Eligibility Manager
2. In Group or Individual UI (Depending on the program) select a beneficiary you want to add to the program
3. Click action and click add to program
4. Select the program you want them to be added

Expected behaviour: after adding, the beneficiary should now be automatically enrolled to the program.

**Comment by adriancris** [comment]
@emjay0921 
No manual eligibility manager in Programs

**Comment by adriancris** [comment]
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/a4bd62fe-63a0-4bb5-80f3-e527e65e839b)

**Comment by emjay0921** [comment]
Will recheck on this today.

**Comment by anthonymarkQA** [comment]
Findings: Blocked.

The create program button in ACF DEV instance is not working. and displays an error message on click.
![image](https://github.com/user-attachments/assets/8a593034-bf27-4640-b1aa-568209b5094a)

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV

Unable to find expected feature, "manual eligibility manager"


![Image](https://github.com/user-attachments/assets/efe3833d-cccb-4784-b6d4-1cae7e12de04)

**Comment by emjay0921** [comment]
Created new [PR](https://github.com/OpenSPP/openspp-modules/pull/481) for the update on the Manual Eligibility Manager Fixes.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Should be able to select manual eligibility when creating program under eligibility manager - pass
![image](https://github.com/user-attachments/assets/e66aa0b3-29d6-4555-9da6-a284af5cc3bb)

Should be able to add individual to a program targeted for individual - pass
Should not be able to add group to a program targeted for individual - pass
Should be able to add group to a program targeted for group - pass
Should not be able to add individual to a program targeted for group - pass


Note: only way to unenroll a beneficiary to a manual eligibility enabled program is by deleting the beneficiary from the program and/or cycle
