### ISSUE TITLE
Development of spp_base_gis module

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#344]
Objective:
To have our own GIS engine where we can plot vectors (Point, Line, Polygon) on a map by utilizing the maptiler JS and to have our own customized view where we can see on the map all of the vectors of the record.

Features:
- base module for GIS where a customized field will be set that will automatically render a Map whenever the field is called on the UI.
- a new customized view that will collect all of the vectors of all of the records of a model and show all of them in the map
- Able to customize the vectors
- Able to customize the UI of the map in the new customized view
- Able to add a raster layer in the new customized view
- Able to search for a country and city
- Able to click the vectors to show the details of the record
- Able to get the currect location of the device
- Able to search a specific record

**Comment by reichie020212** [comment]
Below are the list of MapStyle that is available in MapTiler
- BACKDROP
- BASIC
- BRIGHT
- DATAVIZ
- HYBRID
- OCEAN
- OPENSTREETMAP
- OUTDOOR
- SATELLITE - This is the default
- STREETS
- TONER
- TOPO
- VOYAGER
- WINTER

**Comment by reichie020212** [comment]
References
MapTiler - https://docs.maptiler.com/sdk-js/api/
MapBox Draw - https://github.com/mapbox/mapbox-gl-draw
Mapbox Draw with sample on calculating area - https://docs.maptiler.com/sdk-js/examples/mapbox-gl-draw/
Turf JS (for the calculation of the geoJson) - https://turfjs.org/
Control Style Switcher - https://docs.maptiler.com/sdk-js/examples/control-style-switcher/ (we already have this via raster layer but this doc have a different UI and different approach, the cons here is that we need to find static images for the variants of every map style)
Vector layer helper (might be useful) - https://docs.maptiler.com/sdk-js/examples/helper-polyline-minimal/

**Comment by reichie020212** [comment]
MapTiler API key should be stored in the System Parameters with a key "spp_base_gis.map_tiler_api_key"

**Comment by adriancris** [comment]
@reichie020212 
bug found in the GIS. dev is currently fixing.

ISSUE: Radio button does not stay on the selected raster after navigating data layer and/or hiding the sidebar

STEPS TO REPLICATE:

1. Go to GIS View
2. Select a raster.
3. Hide the sidebar.
4. Unhide the sidebar.
5. Raster radio button goes back.

INSTANCE: ACF-DEV

SCREENSHOTS/SCREEN RECORDING:
https://github.com/OpenSPP/openspp-modules/assets/138551361/9433a484-86fc-43d2-b1bc-0b793c78e19a

**Comment by dasunhegoda** [comment]
@reichie020212 has fixed this.
