### ISSUE TITLE
rename `registrant1` and `registrant2` to `from` `to` in G2PRegistrantRelationship

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#35]
- [ ] rename registrant1 and registrant2 to `from` `to` @emjay0921: do this ASAP
- [ ] Automatically generate the reverse relation and keep it updated with the other one: @jeremi will work on it.
- [ ] Update the UI @emjay0921

**Comment by jeremi** [comment]
Make sure to update all the other apps that depends on it

**Comment by emjay0921** [comment]
@jeremi may I ask what needs to be changed or updated on the UI?

**Comment by emjay0921** [comment]
I pushed the update for the renaming of registrant 1 and 2 to source and destination. And PR it also.
