### ISSUE TITLE
VC Implementation

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#372]
Objective: VC - (verifiable credentials)

Description: Add VCI issuer ID in Registry for both groups and individual pages

test cases:

- Should be able to successfully setup encryption page
- Should be able to successfully setup VCI issuer in configuration in its settings
- Should be able to successfully print VCI ID in individual and groups pages.

**Comment by reichie020212** [comment]
- Created spp_encryption module based on g2p_encryption module to supply an encryption type name JWCrpyto in the Encryption Providers page
- Created spp_openid_vci module based on g2p_openid_vci module to do the following
-- Get the Verifiable Credential of the Registry
-- Create a QR Code based on the Verifiable Credential
-- Create an ID Card for the Registry with the embedded QR Code
-- Created a wizard for Registry to select which VCI Issuer to use
-- Automatically fill-up the field Auth Allowed Issuers of VCI Issuers

- Created spp_openid_vci_individual module based on spp_openid_vci, this module is specific for Individual Registry
-- this module added a button named `Issue Card` in the Individual Registry form page.
-- modify VCI Issuer to change the default credential format for Individual Registry
-- modify VCI Issuer to change the default credential type for Individual Registry

- Created spp_openid_vci_group module based on spp_openid_vci, this module is specific for Group Registry
-- this module added a button named `Issue Card` in the Group Registry form page.
-- modify VCI Issuer to change the default credential format for Group Registry
-- modify VCI Issuer to change the default credential type for Group Registry

**Comment by reichie020212** [comment]
Need to replace the `ID Card` text to OpenSPP Logo

**Comment by adriancris** [comment]
@reichie020212 
Dev unable to install module

![image](https://github.com/OpenSPP/openspp-modules/assets/138551361/03bb7c8d-a88b-42a2-bfcf-2c00dc16a7bc)
![image](https://github.com/OpenSPP/openspp-modules/assets/138551361/ca53e2bc-e602-4913-a1a2-f5368678186d)

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev

testing blocked because it is uninstallable in ACF DEV


![image](https://github.com/user-attachments/assets/8f795ba8-d636-4bf1-912f-07993d35c537)
CC: @dasunhegoda

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev

i cannot activate the VCI modules 


![Image](https://github.com/user-attachments/assets/f787e313-5c38-47c0-9fa3-51bf7e7df3ee)

**Comment by reichie020212** [comment]
Note: below are the steps on how to replicate the issue on local
- Create a new fresh database
- install g2p_openid_vci_rest_api
- uninstall g2p_openid_vci
- restart odoo server
- install again g2p_openid_vci_rest_api

**Comment by reichie020212** [comment]
`KeyError: 'odoo.addons.g2p_openid_vci_rest_api.schemas.openid_vci.CredentialBaseResponse` shows when trying to install the module `g2p_openid_vci_rest_api`.

Still unable to find the cause of issue, it seems that we need help from openg2p devs since this is their module

**Comment by reichie020212** [comment]
Found a fix or workaround to fix this issue
If we encounter the error `KeyError: 'odoo.addons.g2p_openid_vci_rest_api.schemas.openid_vci.CredentialBaseResponse` when installing `g2p_openid_vci_rest_api` module or any module that have dependency to this module, we need to uninstall first the `extendable` module then proceed in install the module you want to install.

**Comment by reichie020212** [comment]
Found a fix or workaround to fix this issue
If we encounter the error `KeyError: 'odoo.addons.g2p_openid_vci_rest_api.schemas.openid_vci.CredentialBaseResponse` when installing `g2p_openid_vci_rest_api` module or any module that have dependency to this module, we need to uninstall first the `extendable` module then proceed in installing the module you want to install.

**Comment by kneckinator** [comment]
PR has been approved, but issue status is "in review". What's the next step?

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev

An odoo error appears when attempting to issue a card.

Steps to replicate:

1. Prepare an spmis instance in runboat
2. login as admin
3. Install module spp_openid_vci_individual
4. Go to settings and click Activate the developer mode
5. Go to Settings -> User & Companies -> Users.
6. Enter the record Administrator.
7. Go to Access Rights tab and check the Crypto Admin Role
8. Refresh the page. You should now be able to see the Encryption Providers Menu on top of the page. Click that menu.
9. Enter the Default encryption provider record.
10. In Type field, select the JWCrypto then Click the button Create Jwcrpyto Key then Save.
11. Go to VCI Issuer menu and create a record.
12. Fillup only the following: Name, Scope, Issuer Type, Supported Format, Encryption Provider, and Auth Subject ID Type
13. Upon saving, other fields will be automatically fill-up.
14. Go to Registry -> Individuals and create a record.
15. Make sure the the Individual have an ID type with the same ID Type selected in Auth Subject ID Type
16. Click the Issue Card button in the top-middle of the page.
17. Select the Issuer that was created earlier then click Confirm.
18. Notice upon clicking confirm, an odoo error appears

![image](https://github.com/user-attachments/assets/a4fa173c-4d8b-433a-becc-4eed62607ec5)

Attached below is the odoo error
[odoo error text.txt](https://github.com/user-attachments/files/17145979/odoo.error.text.txt)

**Comment by celinenilla** [comment]
@anthonymarkQA , retest after the merge of missing modules that was done earlier this week

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev.

Similar issue, upon clicking confirm. an odoo error appears, but this time it has a different odoo error message
[odoo.error.text  2nd.txt](https://github.com/user-attachments/files/17241255/odoo.error.text.2nd.txt)

**Comment by reichie020212** [comment]
upon checking, the API that is needed to send request is returning a 500 error with below response

{'detail': 'Internal Server Error'}

here is the API
 http://openspp-openspp-modules-17-0-adf9c3e640dc.runboatk8.newlogic-demo.com/api/v1/vci/.well-known/openid-credential-issuer/Name

so i think this is a runboat issue, is there any instance we can test aside from runboat?

**Comment by reichie020212** [comment]
I will improve the code on this ticket since an appropriate error message should be displayed if the API is not working

**Comment by jannahadlaon** [comment]
Findings: Returned to dev

An odoo error appears when attempting to issue a card.

Steps to replicate:

1. Prepare an spmis instance in runboat
2. login as admin
3. Install module spp_openid_vci_individual
4. Go to settings and click Activate the developer mode
5. Go to Settings -> User & Companies -> Users.
6. Enter the record Administrator.
7. Go to Access Rights tab and check the Crypto Admin Role
8. Refresh the page. You should now be able to see the Encryption Providers Menu on top of the page. Click that menu.
9. Enter the Default encryption provider record.
10. In Type field, select the JWCrypto then Click the button Create Jwcrpyto Key then Save.
11. Go to VCI Issuer menu and create a record.
12. Fillup only the following: Name, Scope, Issuer Type, Supported Format, Encryption Provider, and Auth Subject ID Type
13. Upon saving, other fields will be automatically fill-up.
14. Go to Registry -> Individuals and create a record.
15. Make sure the the Individual have an ID type with the same ID Type selected in Auth Subject ID Type
16. Click the Issue Card button in the top-middle of the page.
17. Select the Issuer that was created earlier then click Confirm.
18. Upon clicking confirm, an odoo error appears:

Access Error 
Failed to get credential issuer data. Status code: 500
![image](https://github.com/user-attachments/assets/15758cb1-b5b1-4453-827c-fa8bc2bd56c2)
cc: @reichie020212

**Comment by reichie020212** [comment]
already reported to @kneckinator the issue, it seems this is a runboat issue since the runboat cannot access its own API endpoint, but when tested to acf-dev instance, it is working

**Comment by celinenilla** [comment]
Since we have issues testing this on runboat, it was agreed to test this on qa spmis instance and then merge the final ticket for the error message once all else is working as expected.

**Comment by jannahadlaon** [comment]
Findings: **Return to dev**
Instance: https://qa-sp-mis.newlogic.net/web?debug=1#cids=1&menu_id=219&action=333&model=res.partner&view_type=form&id=666
An odoo error appears when attempting to issue a card.

**Steps to replicate:**
1. Prepare an spmis instance in runboat
2. login as admin
3. Install module spp_openid_vci_individual
4. Go to settings and click Activate the developer mode
5. Go to Settings -> User & Companies -> Users.
6. Enter the record Administrator.
7. Go to Access Rights tab and check the Crypto Admin Role
8. Refresh the page. You should now be able to see the Encryption Providers Menu on top of the page. Click that menu.
9. Enter the Default encryption provider record.
10. In Type field, select the JWCrypto then Click the button Create Jwcrpyto Key then Save.
11. Go to VCI Issuer menu and create a record.
12. Fillup only the following: Name, Scope, Issuer Type, Supported Format, Encryption Provider, and Auth Subject ID Type
13. Upon saving, other fields will be automatically fill-up.
14. Go to Registry -> Individuals and create a record.
15. Make sure the the Individual have an ID type with the same ID Type selected in Auth Subject ID Type
16. Click the Issue Card button in the top-middle of the page.
17. Select the Issuer that was created earlier then click Confirm.
18. Upon clicking confirm, an odoo error appears:

Odoo Error
![image](https://github.com/user-attachments/assets/72d9d86c-041f-4abd-866b-02c6a0ed7f2c)
Error:

> RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/addons/extendable/models/ir_http.py", line 20, in _dispatch
    return super()._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/spp_openid_vci/wizard/vci_issuer_selection.py", line 12, in issue_card
    return self.partner_id._issue_vc_qr(self.issuer_id)
  File "/opt/odoo/addons/spp_openid_vci/models/res_partner.py", line 113, in _issue_vc_qr
    result = self._issue_vc(vci_issuer)
  File "/opt/odoo/addons/spp_openid_vci/models/res_partner.py", line 48, in _issue_vc
    issuer_data = credential_issuer_response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://qa-sp-mis.newlogic.net/web/assets/60a0582/web.assets_web.min.js:2894:163)
        at XMLHttpRequest.<anonymous> (https://qa-sp-mis.newlogic.net/web/assets/60a0582/web.assets_web.min.js:2898:13)

**Comment by kneckinator** [comment]
Issue with Runboat has been addressed. A PR to persist this can be found at https://github.com/OpenSPP/runboat/pull/7

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**

**Steps**:
1. Prepare an spmis instance in runboat
2. login as admin
3. Install module spp_openid_vci_individual
4. Go to settings and click Activate the developer mode
5. Go to Settings -> User & Companies -> Users.
6. Enter the record Administrator.
7. Go to Access Rights tab and check the Crypto Admin Role
8. Refresh the page. You should now be able to see the Encryption Providers Menu on top of the page. Click that menu.
9. Enter the Default encryption provider record.
10. In Type field, select the JWCrypto then Click the button Create Jwcrpyto Key then Save.
11. Go to VCI Issuer menu and create a record.
12. Fillup only the following: Name, Scope, Issuer Type, Supported Format, Encryption Provider, and Auth Subject ID Type
13. Upon saving, other fields will be automatically fill-up.
14. Go to Registry -> Individuals and create a record.
15. Make sure the the Individual have an ID type with the same ID Type selected in Auth Subject ID Type
16. Add Birthdate, Gender, and Address then save
17. Click the Issue Card button in the top-middle of the page.
18. Select the Issuer that was created earlier then click Confirm.
19. Verify that an ID in PDF format is automatically downloaded.
![image](https://github.com/user-attachments/assets/cdb7be6f-7cb7-4a9a-b92d-2361b81558b9)
