### ISSUE TITLE
Modify the behavior of compute fields for our computed fields used for criterias

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#4]
The addition of new computed fields on res.partners would be quite common in our system. So we need to make it easy to use.
Right now, if you have a large amount of data, it often fails to install an app.

So we need to:

- Do not recompute additional fields when installing an app but store them to be run in a queue using Celery ( https://github.com/newlogic/newlogic-g2p/issues/1 )

- Recompute directly only if few records are impacted (Less than 10)

- Use celery to re-compute them

**Comment by gonzalesedwin1123** [comment]
Modified to use OCA queue_job

**Comment by gonzalesedwin1123** [comment]
Latest Updates:
- Used OCA job_queue instead of celery.
- Added system settings in menu "Configuration->Settings" to allow changing the max registrants to process before running job queue and number of participants per batch.
- Notifications that the process will be done by job_queue and completion of the job are sent to members of the "g2p_registry_base.group_g2p_admin" group.
TODOs:
- Batch processing. Needs to find a way to divide the recordset(value of self passed to function: _compute_count_and_set) by batch count then run the function in job queue.

**Comment by gonzalesedwin1123** [comment]
Latest Updates:

- The function: _compute_count_and_set call to count_individuals will generate and execute a single query to generate values for all record's compute fields that needs to be updated.
- The function: query_members_aggregate generates a list of dict with this format:
[{'id': 1, 'members_cnt': 3},
 {'id': 5, 'members_cnt': 6}
]

**Comment by gonzalesedwin1123** [comment]
Modified the process of updating the compute fields using SQL update statement.

**Comment by jeremi** [comment]
I added more comments, and did some refactor, but make sure it still work.

**Comment by gonzalesedwin1123** [comment]
Modified the process of updating the compute fields using a single SQL update statement.
