### ISSUE TITLE
Set Apps icons

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#40]
Take the icons from the website: https://openspp.org/features/
If you need modifications or new ones, ask Lit
To set the icons, do this in OpenSPP repository. We will need another set for OpenG2P

**Comment by jeremi** [comment]
This is needed for:
- The apps (if no icon, set the OpenSPP or OpenG2P icon)
- Menus (needed in particular when we enable the web_responsive)

**Comment by emjay0921** [comment]
PUSHED

OpenSPP

1. [openspp-registry](https://github.com/openspp-project/openspp-registry) - [PR](https://github.com/openspp-project/openspp-registry/pull/45)
- spp_area: OpenSPP Logo
- spp_consent: OpenSPP Logo
- spp_custom_field: OpenSPP Logo
- spp_custom_fiels_ui: OpenSPP Logo
- spp_idpass: OpenSPP ID Logo
- spp_idqueue: OpenSPP ID Logo
- spp_photo: OpenSPP Logo

2. [openspp-program](https://github.com/openspp-project/openspp-program) - [PR](https://github.com/openspp-project/openspp-program/pull/16)
- g2p_entitlement_cash: OpenG2P Logo
- spp_dashboard: OpenSPP Logo
- spp_entitlement_in_kind: OpenSPP Logo
- spp_pos: OpenSPP Logo

3. [openspp-demo](https://github.com/openspp-project/openspp-demo) - [PR](https://github.com/openspp-project/openspp-demo/pull/18)
- g2p_connect_demo1: OpenG2P Logo
- spp_base_demo: OpenSPP Logo
- spp_demo: OpenSPP Logo

4. [openspp-grievance-redress-mechanism](https://github.com/openspp-project/openspp-grievance-redress-mechanism) - [PR](https://github.com/openspp-project/openspp-grievance-redress-mechanism/pull/2)
- spp_helpdesk: OpenSPP Logo

5. [openspp-communication](https://github.com/openspp-project/openspp-communication) - [PR](https://github.com/openspp-project/openspp-communication/pull/1)
- spp_sms: OpenSPP Logo

6. [openspp-theme](https://github.com/openspp-project/openspp-theme) - [PR](https://github.com/openspp-project/openspp-theme/pull/1)
- theme_openspp: OpenSPP Logo

OpenG2P

1. [openg2p-registry](https://github.com/OpenG2P/openg2p-registry) - [PR](https://github.com/OpenG2P/openg2p-registry/pull/24)
- g2p_bank: OpenG2P Logo
- g2p_registry_base: OpenG2P Logo
- g2p_registry_group: OpenG2P Logo
- g2p_registry_individual: OpenG2P Logo
- g2p_registry_membership: OpenG2P Logo
- g2p_registry_rest_api: OpenG2P Logo
- g2p_registry_rest_api_extension_demo: OpenG2P Logo

2. [openg2p-program](https://github.com/OpenG2P/openg2p-program) - [PR](https://github.com/OpenG2P/openg2p-program/pull/5)
- g2p_programs: OpenG2P Logo
