### ISSUE TITLE
Unable to create a program as Program manager

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#422]
When creating a program logged in as program manager. it will display an odoo error message upon clicking admin area,

Web instance:
https://openg2p-sanity.newlogic-demo.com/web/login

kindly see video attached for reference:
https://drive.google.com/file/d/1A3QQloktaFFSd4jzy6wB-mC4Rzwe3du0/view?usp=drive_link

Investigate - Red
- it seems that this is an OpenSPP Issue since Program Manager doesn't have access rights to spp.area

**Comment by jannahadlaon** [comment]
This is working as expected in:
https://qa-sp-mis.newlogic.net/
