### ISSUE TITLE
Fix critical vulnerability in OpenFN

### ISSUE THREAD

**Issue by dasunhegoda** [openspp-project/openspp-registry#425]
https://app.snyk.io/org/jeremi/project/8d265a36-c1a0-43fc-b440-6a7c70a8d862

**Comment by kneckinator** [comment]
Could this be fixed by syncing the upstream OpenFn branch?
![image](https://github.com/user-attachments/assets/2be2b588-e08a-4706-9eea-19c649298fde)

https://github.com/OpenSPP/openfn-adaptors

**Comment by gonzalesedwin1123** [comment]
> Could this be fixed by syncing the upstream OpenFn branch? ![image](https://github.com/user-attachments/assets/2be2b588-e08a-4706-9eea-19c649298fde)
> 
> https://github.com/OpenSPP/openfn-adaptors

I have done this.

**Comment by gonzalesedwin1123** [comment]
I am closing all Snyk PRs

**Comment by gonzalesedwin1123** [comment]
@dasunhegoda please check if this can be closed.

**Comment by dasunhegoda** [comment]
@gonzalesedwin1123 : The vulnerability is still there. You can find the more details in synk

**Comment by kneckinator** [comment]
@dasunhegoda this is a fork of OpenFn – unless we raise a ticket against their repo to address this, there is nothing to do from our side.

However, I see that our fork is still behind the upstream and that we have deviating commits in `main`. I will discard these, as any code we develop for the OpenFn-OpenSPP adaptors should 1) be based on current upstream OpenFn `main` branch and 2) our changes should be PRs against the upstream.

**Comment by dasunhegoda** [comment]
Noted above. @gonzalesedwin1123 FYI

As discussed with @kneckinator, I have removed the OpenFN repo from Synk's repo list.
