### ISSUE TITLE
Remove items not in use (OpenG2P)

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#43]
Following items need to be removed:
- Remove “Salesperson”, “Company”, “Country” (both “Individuals” and “Groups”) (# 1 in linked document)
- Remove “Individuals”, “Companies” (both “Individuals” and “Groups”) (# 2 in linked document)
- Remove filters not in use under Custom filters (both “Individuals” and “Groups”) (# 3 in linked document)
- Remove irrelevant “Tags” (# 5 in linked document)
- Remove “Duplicate” on “Group” (# 25 in linked document)

Linked document for screenshots: https://docs.google.com/document/d/18qaLelNUjKHcBlH0JtukIG8_Y6-2Q_C5ldjP6HKAH4Q/edit

**Comment by emjay0921** [comment]
Remaining task on this list. The other 4 was already merged with this [PR](https://github.com/OpenG2P/openg2p-registry/pull/22)
- [ ] Remove filters not in use under Custom filters (both “Individuals” and “Groups”)

**Comment by nhatnm0612** [comment]
> Remaining task on this list. The other 4 was already merged with this [PR](https://github.com/OpenG2P/openg2p-registry/pull/22)
> 
> * [ ]  Remove filters not in use under Custom filters (both “Individuals” and “Groups”)

#136 may do the rest
