### ISSUE TITLE
Validator HQ is unable to validate Change Request in QA Farmer Registry

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#435]
_Description:_
Error displayed when Validator HQ is validating a Change Request in QA Farmer Registry

_Login_:
crvhq@sample.com | admin123

_Actual Behavior_:
Error displayed when Validator HQ is validating a Change Request

Invalid Operation:
User CR Validator HQ does not have access to apply changes.AccessError("You are not allowed to create 'Land Record Details' (spp.land.record) records.\n\nThis operation is allowed for the following groups:\n\t- OpenG2P Module Access/Administrator\n\nContact your administrator to request access if necessary.")

_Expected Behavior_:
Validator HQ should be able to validate a Change Request

_Instance_:
Farmer Registry QA Instance

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/9d609299-fc4f-406c-80d7-663bf8b45b0a)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Able to create a change request edit information - pass
Should be able to validate sa localCRapprover - pass
![image](https://github.com/user-attachments/assets/600591bc-dfc5-4108-a487-c8e2b0e34511)
Should be able to validate as HQCRapprover - pass
![image](https://github.com/user-attachments/assets/2efdf470-2978-47df-a750-901af53595d0)
Should reflect change into targeted user - pass
![image](https://github.com/user-attachments/assets/48df4ecc-fa13-4b8f-9d08-d792f9865d13)
