### ISSUE TITLE
Fix Error in audit log unable to delete audit rule and error on view logs

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#436]
Install audit log

Test audit log features

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV

Install and activate audit log modules(spp_audit_log, spp_audit_config, spp_audit_post) -  Fail, Unable to activate spp_audit_config

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Install and activate audit log modules (spp_audit_log, spp_audit_config, spp_audit_post) - pass
Should be able to delete audit rules - pass
Should be able to edit audit rules - pass
Should be able to create audit rules - pass
Audit log should appear every record update - pass
Audit log should not be distorted in GUI - pass
