### ISSUE TITLE
Unique ID of new Individual and Group changes

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#438]
_Description_:
Unique ID of new Individuals and Groups changes when saving manually.

_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Navigate to Registry > Individuals or Registry > Groups.
2. Click New.
3. Note the Unique ID
4. Populate the required fields.
5. Save manually.
6. Check Unique ID is different from Unique ID in Step 3.

_Actual Behavior_:
Unique ID of new Individuals and Groups changes when saving manually.

_Expected Behavior_:
Unique ID of new Individuals and Groups SHOULD NOT change when saving manually.

_Recording_:
https://github.com/OpenSPP/openspp-modules/assets/138551361/2511b453-d8a9-4ec6-bf5b-3b588be0690c

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Test case:
Create new group should have consistent Unique ID - Unique ID is generated only upon saving (PASS)
Edit existing group should have consistent Unique ID- PASS

Create new individual should have consistent unique ID - Unique ID is generated only upon saving (PASS)
Edit existing individual should have consistent Unique ID - PASS
