### ISSUE TITLE
Misaligned fields in Entitlement Manager

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#440]
_Description_:
Misaligned fields in Entitlement Manager -- ID Type to store in entitlements and Store Service Points to Entitlements

_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Navigate to Programs.
2. Click Create Program.
3. Click Configure the Entitlement Manager tab.
4. Check alignment of **ID Type to store in entitlements** and **Store Service Points to Entitlements fields**.

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/2c455ef2-5cf3-49b1-9ad1-76bcf4279b84)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Misalingment of ID Type to store in entitlements and Store Service Points to Entitlements fields should be fixed - PASS
![image](https://github.com/user-attachments/assets/01be96f7-c0ec-42cf-8833-bf5e3d466dad)
