### ISSUE TITLE
Two Service Points columns in In-kind Entitlements

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#441]
_Description_:
There are two Service Points columns in In-kind Entitlements. 

_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Create a Program with in-kind entitlement.
2. Create a Cycle.
3. Prepare Entitlements.
4. Click Entitlements.
5. Check columns in Entitlements table.

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/e753eada-4a35-4533-8cf0-4625dbd86aef)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested in ACF DEV instance
Should have only one Service point column  in entitlement page- PASS
![image](https://github.com/user-attachments/assets/eaee1d3d-527e-4eaf-8418-03053f39142c)
