### ISSUE TITLE
No Create SP User button in Service Point

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#442]
_Description_:
There is no Create SP User button after a company has been associated in service point.

_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Navigate to Contacts then click Create.
2. Select Company radio button.
3. Provide Company Name and Company Email Address.
4. Click Save.
5. Navigate to Service Points then click Create.
6. Provide Agent Name then select the Company created in Step 4.
7. Check if Create SP User button is displayed.

_Actual Behavior_:
No Create SP User button displayed.

_Expected Behavior_:
Create SP User button should be displayed.

_Screenshot_:
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/de76022f-19e5-4a66-89e9-4144dea572aa)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested in ACF dev instance
Able to create SP user successfully
![image](https://github.com/user-attachments/assets/a1da1954-d228-41c1-b90b-5cfa34981dc2)
