### ISSUE TITLE
Program is not displayed under a Service Point

### ISSUE THREAD

**Issue by adriancris** [openspp-project/openspp-registry#443]
_Description_:
When a service point is associated with an entitlement, the Program where that entitlement belongs should be displayed in the Service Point table.

_Instance_:
ACF-DEV

_Steps to reproduce_:
1. Assign a Service Point to a Group.
2. Create Program with Group type.
3. Tick Store Service Points to Entitlements checkbox in Entitlement Manager.
4. Create Cycle then Prepare Entitlement.
5. Click Entitlements and check if Service Point is assigned to Group in Step 1.
6. Go to Service Point page.
7. Check if the Program created is under the Service Point assigned.

_Actual Behavior_:
Program is not displayed under a Service Point

_Expected Behavior_:
Program should be displayed in the Service Point when the entitlements of that program is associated to the service point.

_Screenshot_:
No program column
![Image](https://github.com/OpenSPP/openspp-modules/assets/138551361/fce6b516-0b04-4110-997d-6fc91603eabd)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Display program associated with the service point in service point table - pass
Display multiple programs associated with the service point - pass
Display program name as ellipsis for long program names - pass

![image](https://github.com/user-attachments/assets/80aa1379-d184-4d4e-964f-36fb542e8c72)
