### ISSUE TITLE
Fix Compliance Criteria UI inside of Program page

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#451]
Fix below UI Issue on The `Configuration` tab of Program

![image](https://github.com/user-attachments/assets/c5ede4f5-c0f6-4e91-a71b-0d5e48de7564)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested in acf dev

Fix compliance manager table UI distortion - Pass
![image](https://github.com/user-attachments/assets/8c41c87e-9b3b-44c4-a671-698b45d06e52)
