### ISSUE TITLE
Improve Area Import to accomodate coordinates

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#453]
Add `latitude` and `longitude` column in the humdata and improve the area import to accomodate these two new columns of humdata

**Comment by reichie020212** [comment]
[lao-lo-import-new.xlsx](https://github.com/user-attachments/files/16372864/lao-lo-import-new.xlsx)

sample xlsx

**Comment by anthonymarkQA** [comment]
Findings: QA passed

Should not allow upload when an error is encountered within the file during validate - pass
![image](https://github.com/user-attachments/assets/93e628ec-667e-4954-9b15-00f353b67d17)

Able to upload import file including the new columns longitude and latitude values - pass
![image](https://github.com/user-attachments/assets/e80773fc-bf10-45ac-8d0e-ef8dfa24fc1d)
![image](https://github.com/user-attachments/assets/79474b1c-15d5-41b3-8f1f-e285c7423664)
