### ISSUE TITLE
Added Translation in Area Import

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#464]
Import area should support translation of area names in one excel file, there should be no limit on how many translation are included in the excel file.

**Comment by reichie020212** [comment]
[lao-lo-import-new.xlsx](https://github.com/user-attachments/files/16832934/lao-lo-import-new.xlsx)
sample

**Comment by anthonymarkQA** [comment]
Findings: Need to discuss limitation

Able to translate Area language using translations from CSV uploaded - PASS

Limitation:
This feature will only work if, first, the preferred language was activated, then the file with the preferred language is uploaded.
Uploading the csv first then activating the preferred language will not translate the values.

**Comment by reichie020212** [comment]
@anthonymarkQA Additional features/content:
- Add an error message if one of the languages in the file is not activated in the system.
- Add an instruction in the error message that says "asks admin to activate the language <language name>"

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV

Validation if the language is activated is not working.
![image](https://github.com/user-attachments/assets/eae5697c-7ad5-4c05-ab50-515103ff56c1)

**Comment by reichie020212** [comment]
Update: Still investigating the issue on runboat not recognizing the new method for the model `spp.area.import`. Already reported this issue to ken.

**Comment by celinenilla** [comment]
@reichie020212 to follow up on comments from @kneckinator

**Comment by kneckinator** [comment]
Issue with runboat has been solved, where dependencies from external components where downgrading six OpenSPP components to use openspp-modules@17.0, which effectively would downgrade them to use the 17.0 branch instead of the branch specified when creating the runboat instance.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested in a runboat instance bf6fbed79-05b0-4fe4-aba5-099e6b5cb744
When import button is clicked, allow import if alternate language in csv is already activated - PASS

When import button is clicked, validation error message appears if the alternate language in the csv is not yet activated - PASS
![image](https://github.com/user-attachments/assets/cae7fa29-e86f-43ac-a0ab-8ff5f5fb4790)
