### ISSUE TITLE
Fix Service Point form view UI

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#471]
fields in Service Point is not aligned correctly 

![Image](https://github.com/OpenSPP/openspp-modules/assets/35404367/bdb267db-08dc-482c-9898-adcc54fd1673)

**Comment by anthonymarkQA** [comment]
Findings:  QA Passed

Should align input fields for service points - Pass

![image](https://github.com/user-attachments/assets/8d40730c-2d5c-43cf-a33f-8fe28fa78aa1)
