### ISSUE TITLE
Farmer Tab data registry issue

### ISSUE THREAD

**Issue by jannahadlaon** [openspp-project/openspp-registry#505]
**2 issues were identified in Farmer Tab when registering a Group**
1. When saving Last Name and Given Name in Farmer tab, only the first letter is saved in upper case.
2. Edited Mobile Telephone Number in a Group is not saved

STEPS

1. Go to Registry >> Group >> New
2. Fill Family Name: O'Cronin
3. Fill Given Name: O'Cronin
4. Fill mobile number: 639386498373
5. Save manually: _see issue 1_
       O'Cronin is saved as O'cronin
6. Edit mobile number
7. Save manually: _see issue 2_
       Mobile number is not updated

_see video attached_
https://drive.google.com/file/d/1cy8CLzepoJ6CDBqRTq3LnoMcKagHuxFB/view?usp=sharing

**Comment by emjay0921** [comment]
@jannahadlaon I have linked the PR, let's wait for review and deployment :).

**Comment by kneckinator** [comment]
This ticket is "in review" but the PR has been approved. What is the next step?

**Comment by anthonymarkQA** [comment]
Findings: QA Passed 
tested on farmer registry base on a runboat instance

Should be able to save name without changing its lettercase
![image](https://github.com/user-attachments/assets/b19f046e-898c-4919-8b54-b54a46a4e206)
![image](https://github.com/user-attachments/assets/dc2281f5-5c0b-4762-a3fc-cec606f4f0bf)



Should be able to edit mobile number and save changes - PASS
![image](https://github.com/user-attachments/assets/e11aaaf0-a8f9-40ea-a3a7-c030acb27bdb)
