### ISSUE TITLE
Update the module that installs SP-MIS and Farmer Registry using a wizard

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#506]
Modify the spp_starter module to support the installation of the following:

- [x] SP-MIS
- [x] Farmer Registry

**Comment by anthonymarkQA** [comment]
FIndings: In progress

Test cases:

- Install farmer without demo module
- install farmer with demo module
- install spmis without demo module
- Install spmis with demo module
- export modules activated for farmer and compare to the documentation for farmer base setup module list.
- export modules activated for spmis and compare to the documentation for spmis base setup module list.

**Comment by anthonymarkQA** [comment]
Findings: In Progress


- Activating the spp_starter then clicking on cancel from the wizard modal. User will be unable to return to Apps page.
- Activating the spp_starter does not automatically bring up the wizard modal.

1. install farmer without demo module - pass
2. install farmer with demo module - pass
3. install spmis without demo module - pass
4. Install spmis with demo module - pass

1. export modules activated for farmer without demo and compare to the documentation for farmer base setup module list. - pass
2. export modules activated for farmer with demo and compare to the documentation for farmer base setup module list. - need to review with @reichie020212 
3. export modules activated for spmis without demo and compare to the documentation for spmis base setup module list. - in progress
4. export modules activated for spmis with demo and compare to the documentation for farmer base setup module list. - in progress

Link for modules installed by spp_starter
https://docs.google.com/spreadsheets/d/1gR_9gM2UOrBlMDttnmFKLrA1RTjxJdCFDj45OT099d4/edit?gid=624916670#gid=624916670

**Comment by jannahadlaon** [comment]
Findings: Send back to dev for review

1. install spmis without demo module - PASS
2. Install spmis with demo module - FAIL
> SP-MIS wizard does not have option to install demo module. See video below on timestamp- 00:46.
https://drive.google.com/file/d/1qX_wrsMiaUq6VZSrUjnlDHhVQvL1WNv0/view?usp=sharing

3. export modules activated for spmis without demo and compare to the documentation for spmis base setup module list. - PASS
4. export modules activated for spmis with demo and compare to the documentation for spmis base setup module list. - BLOCKED by 2

cc: @reichie020212 @gonzalesedwin1123 @anthonymarkQA

**Comment by jannahadlaon** [comment]
Findings: QA PASS

Activating the _spp_starter_ does not automatically bring up the wizard modal. Users need to go back to Apps after activating the _spp_starter_ 
_video_:
https://drive.google.com/file/d/16cwy2UkwYBsePjpqByIPon2cMnRHEYD5/view?usp=sharing

1. Install spmis without demo module - PASS
2. Install spmis with demo module - PASS

List of modules installed:
https://docs.google.com/spreadsheets/d/1gR_9gM2UOrBlMDttnmFKLrA1RTjxJdCFDj45OT099d4/edit?gid=1977545584#gid=1977545584
