### ISSUE TITLE
Sort by displaying error values first in area import

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#514]
**Describe the bug**
As improvement,  `Remarks/errors` column should display errors first so that user will not be able to miss on resolving import issues
**To Reproduce**

1. Go to Farmer Regstry QA
2. Login as admin
3. go to Area 
4. Click "Areas" beside Area and it should display "Area import" in one of the list items.
5. Click Area import then upload the file attached in this ticket then click import
6. Click Validate data
7. Notice you dont see a validation error
8. Click on Remarks/errors` column then you should see now the error.

**Expected behavior**
Upon clicking validate data, it should display the Erroneous values first. 
**Screenshots**

![Image](https://github.com/user-attachments/assets/23d8a822-406d-4660-93fd-8ffc3c9f762e)

**Additional context**

[lao-lo-import-new (3).xlsx](https://github.com/user-attachments/files/16596249/lao-lo-import-new.3.xlsx)

**Comment by reichie020212** [comment]
@anthonymarkQA I added two new validations for the latitude and longitude. Kindly add this in your test case. Thanks.

![Image](https://github.com/user-attachments/assets/35fd8170-4f70-4523-a329-062fe1838855)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Errors must appear topmost of the list upon validation of data- PASS

![Image](https://github.com/user-attachments/assets/2a8e7d1f-0134-470e-80c2-3a8ad03c7e74)
