### ISSUE TITLE
Target type in create program modal is not working

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#517]
**Describe the bug**
Switching between Group or Individual as target type when creating a program does not work in farmer registry
**To Reproduce**

1. Go to farmer registry QA and login as admin
2. Click on Programs
3. Click on Create a program
4. Notice in the create program modal, switching between target types does not affect record count that is found.

**Expected behavior**
Switching between group and individual should target the record type accordingly and should not display records unrelated to the selected target type
**Screenshots**

![Image](https://github.com/user-attachments/assets/38956146-6452-4b62-a518-b1030b9235d2)

![Image](https://github.com/user-attachments/assets/f2698265-09df-4e95-a4fb-b2c98cb3b15e)

**Comment by reichie020212** [comment]
Upon checking, the error is due to `spp_programs` module is not installed since the fix for this is only added in `spp_programs`.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

installing programs for farmer registry should also install `spp_programs` as this makes the program module target type work as expected.


![Image](https://github.com/user-attachments/assets/06fbf7e0-e0e4-43ac-b58b-f86b0ac22e3e)

**Comment by kneckinator** [comment]
@reichie020212 I guess there are code changes related to this issue. Could you see if you can link the PR to this issue? Thanks.

**Comment by reichie020212** [comment]
Hi @kneckinator the code related to this was first done in odoo 15 last April 23, 2023 and I am not able to find the PR for that
But i can attach the PR that migrates the code from Odoo 15 to Odoo 17.

**Comment by reichie020212** [comment]
@kneckinator here is the PR https://github.com/OpenSPP/openspp-modules/pull/335, i'm not sure why i can't attach it in this ticket so i'll just put here in the comment section.

**Comment by kneckinator** [comment]
> Upon checking, the error is due to `spp_programs` module is not installed since the fix for this is only added in `spp_programs`.

Seeing this comment, it is likely that the correct status of this issue should be "Closed" with status "Invalid" (which is a status we don't have, so right now I'll use "Won't do"). 

FYI @dasunhegoda @anthonymarkQA
