### ISSUE TITLE
Registry Icon not visible in SPMIS base and farmer registry base instances

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#524]
**Describe the bug**
The icon for registry module is not visible for both spmis and farmer registry base versions, 
**To Reproduce**

1. Go to either spmis or farmer registry QA
2. login as admin
3. Click on the box icon beside "Registry"
4. Notice that "Registry" button does not have icon.

**Expected behavior**
Fix icon for Registry for both spmis and farmer registry base through theme config. Not by installling modules.
**Screenshots**

![Image](https://github.com/user-attachments/assets/807dac00-6888-474d-aed0-116b45421239)

**Additional context**

**Comment by jannahadlaon** [comment]
Issue is still present in :
(https://qa-sp-mis.newlogic.net/web#action=331&model=res.partner&view_type=list&cids=1&menu_id=155)
@gonzalesedwin1123 
![image](https://github.com/user-attachments/assets/d6e95f9b-1bfb-4a7e-9473-14023f0a9f11)

**Comment by jannahadlaon** [comment]
This works as expected now.
Tested in: (https://qa-sp-mis.newlogic.net/)
Thank you @gonzalesedwin1123

**Comment by anthonymarkQA** [comment]
Additional findings for one above: QA Passed

tested in: https://qa-farmer.newlogic.net/web/login


![Image](https://github.com/user-attachments/assets/b4ccddca-ee2b-4b21-8a1a-af8cc1fabc1c)
