### ISSUE TITLE
Display validation error when saving a farmer group without head

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#528]
https://github.com/OpenSPP/openspp-acf/issues/38

Actual:
Able to delete all members for a farmer group including head farmer, and save.

![Image](https://github.com/user-attachments/assets/2b1b7edf-3190-402f-85ca-74cfb11d390e)

Expected:

Must require to have 1 head member per farmer group. else an error should display
Transfer head status from farmer created by farmer tab to another member added via "add a line" should be possible
Delete any members from farmer group except the head member should be possible.
Farmer tab information should always display the information of the current head member of farmer group
Any modification on the head member's information should reflect to both farmer tab, members tab. and in Individuals page.
deleting the head member of farmer group from INDIVIDUALS module should not be possible.
deleting the head member of farmer group from Farmer tab should not be possible

**Comment by anthonymarkQA** [comment]
Findings - QA Passed
Module affected:  spp_farmer_registry_base

1. Must require to have 1 head member per farmer group. else an error should display - PASS
2. Transfer head status from farmer created by farmer tab to another member added via "add a line" should be possible - PASS
3. Delete any members from farmer group except the head member should be possible. - PASS
4. Farmer tab information should always display the information of the current head member of farmer group - PASS
5. Any modification on the head member's information should reflect to both farmer tab, members tab. and in Individuals page. -PASS
6. deleting the head member of farmer group from INDIVIDUALS module should not be possible. - PASS 
7. deleting the head member of farmer group from Farmer tab should not be possible -  PASS
