### ISSUE TITLE
Improve registry template for import group and individuals

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#529]
Actual:
When downloading a template as reference to import group or individual, it is using the same template for both individual and group.
![350331979-e605beff-b6af-43dc-ae39-a7e3322fc92f](https://github.com/user-attachments/assets/7fa52676-e258-442c-8e3e-91b95bf8cb1a)

Expected
Fix template to include fields relevant for each type accordingly(group and individual)
For relevant fields, we may refer to export feature's default fields

Individual
![350331414-53a426fb-70b4-44d7-b4a7-680e029dbc9e](https://github.com/user-attachments/assets/afe2047a-153c-416b-b162-e34fe8e84421)

Group
![350331672-85768c9f-1d2f-4e21-8dd8-e13cace0fee2](https://github.com/user-attachments/assets/be3abb94-8c49-4fbc-bd21-5124053648bd)

**Comment by anthonymarkQA** [comment]
ACF ticket reference: https://github.com/OpenSPP/openspp-acf/issues/31

**Comment by anthonymarkQA** [comment]
Findings: Returned to DEV

Same issue, no applied fixes found.
![image](https://github.com/user-attachments/assets/6be4a78b-6b47-437d-94c4-60246c730778)

**Comment by reichie020212** [comment]
Had a discussion with @anthonymarkQA , will move this ticket to QA.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Prerequisite: Install `spp_registrant_import` module
Group
![image](https://github.com/user-attachments/assets/5665af34-e2b8-474c-bf05-d0b75714dc08)
Individual
![image](https://github.com/user-attachments/assets/7b867b14-9d5c-49d2-b624-233d3fa9d239)
