### ISSUE TITLE
Feature to 'view attachment' from CR requests

### ISSUE THREAD

**Issue by jannahadlaon** [openspp-project/openspp-registry#530]
**Describe the bug**
It should be possible to click a button to view attachments of change requests from the GUI without needing to download the file. Currently , to view attachments associated with the change requests, user must download the attachments first.

**To Reproduce**

**Actual behavior**
To view attachments associated with the change requests, user must download the attachments first.

**Expected behavior**
It should be possible to click a button to view attachments of change requests from the GUI without needing to download the file

**Screenshots**

**Additional context**
This ticket was previously logged in the link below from a repository that has been archived:
[https://github.com/OpenSPP/openspp-acf/issues/39](https://github.com/OpenSPP/openspp-acf/issues/39)

**Comment by anthonymarkQA** [comment]
Findings: QA Passed


View attachment in Change request view
![image](https://github.com/user-attachments/assets/7a8783f8-896f-410b-9b8c-195114915a80)

View attachment in DMS view
![image](https://github.com/user-attachments/assets/bf18ee73-9c55-4dfa-ae24-03baff7639dd)

View attachment in detailed view of CR view in DMS 
![image](https://github.com/user-attachments/assets/1156adef-b30e-4925-a420-dff6b2a8e34c)

The result when clicking the preview button
![image](https://github.com/user-attachments/assets/6c2a30b3-ae2e-4281-86b6-c4341ca1d5f7)



**LIMITATION: This view attachment feature can only preview PDF and image Format files.**
tested using XLSX, CSV, PDF, DOCX.JPEG, PNG
