### ISSUE TITLE
Issue in local registrar unable to view assigned area in registry

### ISSUE THREAD

**Issue by jannahadlaon** [openspp-project/openspp-registry#531]
**Describe the bug**

**To Reproduce**
1. As admin, find an existing user, or create one if there's no user yet
2. Go to Settings> users & companies > roles
3. Select and click local registry
4. Under 'users' tab , add the user you want, then assign that user to an area.
5. Login using that user, then click registry.

**Actual behavior**
The user is unable to access the records in the registry module upon login when assigning a user into a local registrar role despite defining its area.
![Image](https://github.com/user-attachments/assets/513dd47d-b6fa-4fcd-b8e8-9c6b5d4479d2)

**Expected behavior**
User assigned to an area and local registry role should be able to access the records associated with the area defined in the registry

**Screenshots**
![Image](https://github.com/user-attachments/assets/6745ff1f-2cf3-4a4d-8af2-f0f9635c79e1)

**Additional context**
This ticket was previously logged in the link below from a repository that has been archived:
[https://github.com/OpenSPP/openspp-acf/issues/36](https://github.com/OpenSPP/openspp-acf/issues/36
)

**Comment by kneckinator** [comment]
PR has been approved, but the status in "In review". What is the next step?

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested on an spmis build from runboat

Assigning an area(B) to a local registrar user will give CRUD access to registry to the current area(B) and its associated sub-areas(C.1,C.2...) but not its parent area(A) - PASS



![image](https://github.com/user-attachments/assets/df830570-1806-4ed5-8929-6336823a80e8)
![image](https://github.com/user-attachments/assets/4862e410-9f6f-41a1-9c96-7acd6b79d776)
![image](https://github.com/user-attachments/assets/e957b1d1-ee29-42a4-8db8-3239ca26300d)
