### ISSUE TITLE
Manual eligibility issues with configuration tab and verify eligibility button

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#533]
Actual:

When manual eligibility is selected upon creation of program , certain buttons disappear such as import beneficiary, enroll beneficiary and verify eligibility .this is expected as enrolling of individual or group to this program will be through manual adding to the program,
If you go to configuration tab of the program and edit eligibility manager to , for example tag based eligibility, you can do so, however the hidden buttons due to being manual eligibility does not reappear.

![351596542-2fab029c-f300-4c5a-8c4a-b9bf2d311a46](https://github.com/user-attachments/assets/15ec1687-f187-41de-b24d-0215b52e02ab)

Verify eligibility button is still visible and can still be clicked even if a program is configured to manual eligibility
2.a - click on a program configured to manual eligibility > click beneficiaries > notice verify eligibility button.
2.b - click on an individual/group, > click other programs tab > click on a manual eligibility program > notice verify eligibility button
![351596372-38b4416f-3451-4368-9ddd-8167a485c7c2](https://github.com/user-attachments/assets/c881bd50-7c36-4ab2-89a9-5a4de307aaa1)

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev
Prerequisite : Install manual eligibility module.
Issues found:
Verify eligibility button is still visible and interactable for MANUAL ELIGIBLITY setup, clicking it will display na odoo error
![image](https://github.com/user-attachments/assets/21e5733a-2585-499b-b813-9acaf8545b69)

**Comment by emjay0921** [comment]
## **Done adding PR --> Returning to In Review**

## **Why is this change needed?**
To hide `Verify Eligibility` button on cycle view

## **How was the change implemented?**
Added an attribute on cycle view to hide `Verify Eligibility` button if Program is Manual Eligibility

## **New unit tests**
```
None
```

## **Unit tests executed by the author**
```
None
```

## **How to test manually**
- Install or Upgrade `spp_manual_eligibility`.
- Navigate to a Program with Manual Eligibility as the Eligibility Manager.
- Create or Open a Cycle.
- Check if `Verify Eligibility` Button is hidden.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/533

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
prerequisite: install  `spp_manual_eligibility`
Tested in SPMIS runboat instance|

Manual eligibility must not have verify eligibility or import or enroll eligiblity buttons
![image](https://github.com/user-attachments/assets/daf55f58-f8a1-4887-a0cb-ab654200a594)


beneficiary view no more verify eligibility
![image](https://github.com/user-attachments/assets/b3308217-8bbe-4cdf-ae06-ccaf050cdea0)
