### ISSUE TITLE
Able to approve entitlements of a cycle that is still not approved

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#538]
**Describe the bug**
I am able to approve the entitlements within a cycle even though the cycle is still not approved.
**(Kindly review this ticket carefully if it is indeed an issue or not.)**
**To Reproduce**

1. Go to SP-MIS QA and login as QA
2. Click on programs, then select an existing program named "test2"
3. create a new cycle under that program
4. click "prepare entitlements"
5. Instead of clicking "to approve" button, click entitlements tab.
6. highlight the entitlements by ticking the checkboxes
7. click on action button then select approve.
8. A modal should appear. click approve.
9. Notice that i am able to approve the entitlements even if the cycle is not approved yet.

**Expected behavior**

1. Should only be able to approve entitlements if cycle is already approved.
2. Should be applied to OpenSPP that uses program modules.
3. NOTE: if auto approve entitlements is enabled, approving a cycle should automatically set its entitlements to approved if possible.(if funds are enough etc..)

**Screenshots**

![Image](https://github.com/user-attachments/assets/e4c33ca2-4071-424a-bb5c-937f7d664824)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by jannahadlaon** [comment]
Works as expected
Tested in: https://qa-sp-mis.newlogic.net/
![image](https://github.com/user-attachments/assets/affb1961-a8e7-401a-9ace-ac1b11e506b0)
