### ISSUE TITLE
Develop a module for dynamically loading program UI templates

### ISSUE THREAD

**Issue by gonzalesedwin1123** [openspp-project/openspp-registry#555]
Program UIs may have different layouts. Make the necessary fixes to support the dynamic loading of UIs based on the selected program.

**Comment by reichie020212** [comment]
Estimate Dev Time:

Optimistic: 24 hours
Pessimistic: 32 hours

**Comment by emjay0921** [comment]
We might need to have additional field for `g2p.programs` model, specifically a program type. We need this to differentiate the type of program to the functionality to show the correct UI.

cc: @jeremi, @celinenilla. @gonzalesedwin1123

**Comment by jannahadlaon** [comment]
@gonzalesedwin1123 for step 4, this should be the correct UI right?

**STEPS:**
1. Install or Upgrade `spp_programs`.
2. Go to Programs > Create new Program.
3. Under the Currency Field should be a new field called Program UI Template, select one (although this is the generic part the default program UI should be the only one in the selection).
https://drive.google.com/file/d/12VBFL9iGdBFPuSI3Tweq58Yy6tJBD3tf/view?usp=sharing
4. Check if the correct UI is shown when the program is created.
https://drive.google.com/file/d/16vobdX9wUfhCmU-nmzcGMSy2etT_RoX5/view?usp=sharing

**Comment by emjay0921** [comment]
Yes @jannahadlaon , that's the correct UI.

**Comment by jannahadlaon** [comment]
Thanks for clarifying @emjay0921! Moving this ticket to Done.
