### ISSUE TITLE
Split the UI and the demo generator of farmer registry demo module

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#567]
Currently there is no general module for farmer registry base that can be used in production generally, to accomodate this, let's do the following

- Create a new module named `OpenSPP Farmer Registry Default UI`.
- Move the codes of UI of the module `OpenSPP Farmer Registry Demo` to  `OpenSPP Farmer Registry Default UI`
- Retain the generation of demo data in `OpenSPP Farmer Registry Demo`
- `OpenSPP Farmer Registry Demo` module should add in its manifest the `OpenSPP Farmer Registry Default UI` module

**Comment by anthonymarkQA** [comment]
Findings: Returned to dev


Issues Found:
Installing the new module: `OpenSPP Farmer Registry Default UI` seems to not install the farmer specific tabs for the group.
![image](https://github.com/user-attachments/assets/d58c2aa7-9be7-46d9-a61b-cc29155042c5)

Installing `farmer registry Demo ` should ONLY add the **Generate sample data** from configuration and nothing else- Fail (it also adds the farmer registry default Ui like the tabs for the farmer etc..)
![image](https://github.com/user-attachments/assets/c6563412-9f7a-4937-aa9f-f6382e30f06c)



icon of `OpenSPP Farmer Registry Default UI` is broken
![image](https://github.com/user-attachments/assets/e78dede9-a2f1-45aa-8519-8256e1aa309c)

**Comment by anthonymarkQA** [comment]
Hi @celinenilla , as @reichie020212 investigated this ticket and concluded that` Farmer_registry_demo `module comes with additional tabs for the farm group, these additional tabs were created under `farmer_registry_demo` intended to show specific clients what farmer registry could offer more than just the default tabs it has. thats why installing it adds not just the generate sample data button but also additional tabs for the farmer.

to achieve your goal that only generate sample data button will be added when installing "farmer_registry_demo" we can request red to comment out the additional tabs in the farmer_registry_demo module's codes to hide them(additional tabs) for now.

this would also mean i will update the testcases as i am under the assumption that these additional tabs come as default for farmer registry offering.

let us know what you think 

![Image](https://github.com/user-attachments/assets/7a770406-ef36-4021-98fd-5b953cb77e52)

**Comment by celinenilla** [comment]
sounds good, the default ui can do without these three tabs. let's also hide them in the demo module.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Fix farmer registry base default UI app icon - pass
![image](https://github.com/user-attachments/assets/64de4dce-3768-42d7-b65f-0de3e85ab025)

Add necessary farmer tabs in groups when installing `spp_farmer_registry_base ` where this automatically installs `OpenSPP Farmer Registry Default UI` - pass
![image](https://github.com/user-attachments/assets/c4258e32-6f2b-4cb2-9d4d-5d95209bf5d7)

Installing farmer registry demo module should only add generate sample data button - fail(this should be worked on another ticket https://github.com/OpenSPP/openspp-modules/issues/606) as there are modules involved not mentioned in this ticket.
