### ISSUE TITLE
Fix create and write method in farmer registry base

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#569]
Fix the create method in the file `spp_farmer_registry_base/models/farm.py` since it breaks the method of res.partner model to create multiple records in one request. below is the sample code that will produce an error

```
self.env["res.partner"].create([{"name": "Test 1"}, {"name": "Test 2"}])
```

This is a major bug that will break other modules as well if this module is installed.

below is the create method that needs to fix

```
    @api.model_create_multi
    def create(self, vals):
        farm = super().create(vals)
        if farm.is_group:
            self.create_update_farmer(farm)
        elif not farm.is_group and farm.is_registrant:
            self.update_farmer(farm)

        return farm
```

Remove the decorator in the below method

```
    @api.model
    def write(self, vals):
        farm = super().write(vals)

        self._create_update_farmer()

        return farm
```

**Comment by reichie020212** [comment]
Estimate Dev Time:

Optimistic: 4 hours
Pessimistic: 12 hours

**Comment by celinenilla** [comment]
@anthonymarkQA and @reichie020212 , can you two test this together? primarily for @reichie020212 to check that the issue no longer exists and for @anthonymarkQA to verify that everything still working as expected

**Comment by reichie020212** [comment]
@celinenilla @anthonymarkQA , this is @emjay0921 's ticket. But i can still help if someone needs help.

**Comment by reichie020212** [comment]
![Image](https://github.com/user-attachments/assets/a140875f-b45a-4fbb-9ab8-599ab065cc65)
![Image](https://github.com/user-attachments/assets/817adb3e-857e-40bc-ac3c-1c8a91b39de1)
@celinenilla @anthonymarkQA , Done testing the PR in my local and it is working as expected.

in the 1st screenshot, the fix is not yet deployed in my local that's why you can see that the error is showing. In the 2nd screenshot I already deployed the fix the error is not showing anymore

**Comment by anthonymarkQA** [comment]
Additional tests:
QA passed

Should not generate error when running the scheduled action manually in the farmer registry instance with the PR fix- pass
![image](https://github.com/user-attachments/assets/c72c7f8f-0f29-439c-99de-9bd9615195cc)


Should generate error when running the scheduled action manually on a farmer registry isntance without the PR fix - pass
![image](https://github.com/user-attachments/assets/301ce985-1538-43f1-8af3-d5c7e4d847d7)
