### ISSUE TITLE
Unable to use name field under Contact model for Import match feature

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#572]
**Describe the bug**
Duplicates created when using `Name ` field under` Contact` model for Import match feature.
**To Reproduce**

1. login to sp-mis as admin
2. Go to registry>configuration>import match
3. Select `Contact` in Model field
4. toggle on 'overwrite match'
5. Click add a line in Fields 
6. Type `Name` then hit save
7. Import a registrant with a name already existing in the sp-mis instance
8. notice after successfull import, a duplicate is created instead of updating the existing data

**Expected behavior**
Able to use name as unique identifier

**Screenshots**

![Image](https://github.com/user-attachments/assets/0e1dbccc-7d23-4d63-b648-7da75c5ec16e)
![Image](https://github.com/user-attachments/assets/c3ecf905-d863-424a-955c-5f7faf971298)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by reichie020212** [comment]
Estimate Dev Time

Optimistic: 8 hours
Pessimistic: 16 hours

**Comment by emjay0921** [comment]
@anthonymarkQA upon re testing this it is working fine, can you test again?

cc: @celinenilla 

I'm returning this to QA again.

Please see this screen recording for reference:  https://drive.google.com/file/d/1T5WoU6lyRIzQPW2OacwroYYQsUmKneGh/view?usp=sharing

I tested it in this instance: http://openspp-openspp-modules-17-0-ef949748c155.runboatk8.newlogic-demo.com/web#action=180&model=res.partner&view_type=list&cids=1&menu_id=132

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**
Tested in: [http://openspp-openspp-modules-17-0-ef949748c155.runboatk8.newlogic-demo.com/web#action=180&model=res.partner&view_type=list&cids=1&menu_id=132](http://openspp-openspp-modules-17-0-ef949748c155.runboatk8.newlogic-demo.com/web#action=180&model=res.partner&view_type=list&cids=1&menu_id=132)
STEPS
1. login to sp-mis as admin
2. Go to registry>configuration>import match
3. Select Contact in Model field
4. toggle on 'overwrite match'
5. Click add a line in Fields
6. Type Name then hit save
![image](https://github.com/user-attachments/assets/d4e7d03c-588f-44af-87e6-7713b4d4f827)
7. Export registrants you want to update
![image](https://github.com/user-attachments/assets/672976e7-2d45-44c2-b005-df94127f877a)
8. Edit the registrants' `Date of birth` and `Registration date` then import back in the sp-mis instance.
_Before_
![image](https://github.com/user-attachments/assets/0233168f-9c6c-4fe8-8a7a-10f8c4b69e3f)
_Uploaded file_
![image](https://github.com/user-attachments/assets/5c4cd4ad-84a6-4ea8-acfa-5870b1f74ba5)

9. Verify that import was successful and data is reflected correctly
_After_
![image](https://github.com/user-attachments/assets/6b0d9312-89b3-4c43-9138-8ab2aa41e387)
