### ISSUE TITLE
Unable to create Print Batch

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#578]
**Describe the bug**
When attempting to create batch print, an error  "invalid ID type" appears , blocking the batch print process

 **To Reproduce**

1. Go to ACF DEV and login as admin
2. Go to ID Management
3. Click on ID requests Queue
4. Toggle on all checkboxes and click action button
5. Click on Create Batch print
6. A modal should appear, Fill batch name with value
7. Click Save,
8. Notice an error will display "Invalid ID type"

**Expected behavior**
Should be able to proceed on creating batch print
**Screenshots**
![Image](https://github.com/user-attachments/assets/6052ceff-452c-482c-82a9-79d7647006c3)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by reichie020212** [comment]
Estimate Dev Time

Optimistic: 4 hours
Pessimistic: 6 hours

**Comment by anthonymarkQA** [comment]
Findings: QA Passed


Prerequisite to test ticket
Enable developer mode
From settings, go to access rights tab, Enable ID validator role to be able to access ID print batch options from action button

Able to create print batch - pass
![image](https://github.com/user-attachments/assets/95143bce-afb9-4470-a8c9-40740826cbc7)
![image](https://github.com/user-attachments/assets/bc27a928-325e-4071-badc-f3ab6074eb2e)
