### ISSUE TITLE
Fix ID request buttons

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#579]
**Describe the bug**
The buttons related to ID requests are unusually shaped or distorted.
Wizards affected:

- Batch creation
- Multiple ID request
- Single ID request

**To Reproduce**

1. Go to ACF dev and login as admin
2. go to ID management
3. Toggle-on a checkbox with approved status
4. Click action>create batch print
5. Notice the button in the wizard is unusually large

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/3506d1b1-4bed-48db-b9a3-b62ac2e6a03f)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by reichie020212** [comment]
Estimate Dev Time

Optimistic: 4 hours
Pessimistic: 6 hours

**Comment by jannahadlaon** [comment]
This issue is also present in SP-MIS instance @reichie020212

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

Verified in a runboat instance
Prerequisite to test: 
1. Enable developer mode in settings
2. Add "ID VALIDATOR" role to the user account you are using to be able to see ID print batch options from action button in ID management



ID management page buttons in create batch print wizard should be fixed - pass
![image](https://github.com/user-attachments/assets/ada1405d-ea9e-40aa-b086-cf1732532db9)
![image](https://github.com/user-attachments/assets/c96f8746-ccb9-4a10-9eef-f60da54d8594)

Registry page individual and group buttons in Request ID wizard should be fixed - pass
![image](https://github.com/user-attachments/assets/57e9395b-2d11-45e7-9f39-66616ad02f66)
![image](https://github.com/user-attachments/assets/2e7ebb44-0a7a-4601-9279-7da938cfcac5)
