### ISSUE TITLE
Remove nhatnm0612 in .github/auto_assign.yml

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#582]
Remove nhatnm0612 in .github/auto_assign.yml
in the following repo
- openspp-modules
- prj10

**Comment by reichie020212** [comment]
Estimate Dev Time

Optimistic: 4 hours
Pessimistic: 8 hours

**Comment by kneckinator** [comment]
@reichie020212 I do not agree with the provided estimates for this. Evicting from two repos should be a 5-10 minutes operation.

**Comment by reichie020212** [comment]
@kneckinator this estimates are based on days and based on what I know, the lowest value for estimates in days is 0.5 days or 4 hours that's why the optimistic is 4 hours. but yes this ticket can be done in less than 4 hours or 5 to 10 mins to be exact. Thank you.

**Comment by kneckinator** [comment]
nhatnm0612 was also setup as an auto assign in the following repos:
- https://github.com/OpenSPP/openspp-commcare
- https://github.com/OpenSPP/openspp-dms
- https://github.com/OpenSPP/openspp-base
- https://github.com/OpenSPP/openspp-grievance-redress-mechanism
- https://github.com/OpenSPP/openspp-demo
