### ISSUE TITLE
Fix Farmer registry demo module

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#606]
**Describe the bug**
When installing farmer registry demo module it installs `OpenSPP base demo `which then installs `Openg2p Programs`
Thus adding program relate features to the farmer instance.

Also installing farmer registry demo adds values in` higehst educational level ` field in individual .

- Certificate
- Diploma
- University

When selecting either of these three, Certificate, Diploma or University, then save. It will display an odoo error.

**To Reproduce**

1. In Runboat, setup a farmer registry base instance, (do not install farmer registry demo yet)
2. Notice there is no program feature and in Individual>Personal info>Highest educational background, only None, Primary, Secondary and Tertiary) values are available.
3. Go to APPS and install farmer registry demo module
4. Go back in step 2 and notice there are now programs module, and there are new values in Highest educational background which causes odoo error when selected and saved.

**Expected behavior**

After meeting 3 October it was agreed to act on two points:
- Correct the inheritance of select fields (Highest Educational Background and other fields) so that it also inherits the possible values
- Split the demo modules into three; one "SPP Demo Base" which will add generic data such as areas and registry, one "SPP SP-MIS Demo Base" that will add demo data specific to SP-MIS, and one "SPP Farmer Demo Base" which will add demo data specific to Farmer. @gonzalesedwin1123 to summarize what should be included in the different modules

**Screenshots**
![image](https://github.com/user-attachments/assets/e7b1f39d-04a7-4db9-97b8-bd48cbead605)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by reichie020212** [comment]
Upon checking, Certificate, Dimploma, and University are only added when farmer registry demo module is installed since those are defined on this module.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed
Tested on a runboat instance with a farmer registry base configuration



- Installing spp_farmer_registry_base should not auto install spp_demo - pass
- Gender types should not be auto configured/added after installing spp_farmer_registry_base - pass
- Installing spp_farmer_registry_demo should auto install OpenSPP base Demo - pass
- OpenSPP base Demo should not auto install OpenG2P programs - pass
- Installing spp_farmer_registry_demo should add 'Generate sampe farmer data' - pass
- Installing spp_farmer_registry_demo adds three additional highest educational level values in individuals>personal page, - pass
- Installing spp_farmer_registry_demo adds three additional highest educational level values in groups>farmer details page. - pass
- Setting the highest educational background to each of the available values must be able to save for both individuals page and farmer tab page. - pass
- Uninstalling spp_farmer_registry_demo should not have any dependencies on any module. - pass
