### ISSUE TITLE
Attendance Module including API

### ISSUE THREAD

**Issue by celinenilla** [openspp-project/openspp-registry#615]
### Attendance Module API
**Attendee**
Data of the _Individual / Person / Beneficiaries_ would be available on a server1 and would be sent from _Server1_ to _Odoo UI_ via **API1**

**Attendance**
Attendance data of the _Individual / Person / Beneficiaries_ would be available on a server2 and would be sent from _Server2_ to _Odoo UI_ via **API2**. 
**Client ID** and **Client Secret** is required to sync this data.

For testing purpose a `pseudo-postman` inside the UI is to be created. Only _Admin_ would have access to it. Following would be the features required for this postman:
- **Access Token** (POST Get Access Token)
  -  _Client_ would need to be created on UI. Which would provide **Client ID** and **Client Secret**
    -  _Access Token_ would need to be created on Postman? (TBC with Red)
    - Following would be required to be configured on _Odoo UI_:
      - URL and Auth Setting
      - Mappings
- **Create Attendance** (POST Create Attendance)
  - User can create **Attendance** records for each _Individual / Person / Beneficiaries_
- **Get Attendance of a Person** (POST Get Attendance of a Person)
  - User can get all the attendance records for a specific person using this option.
- **Get Attendance List** (POST Get Attendance List)
  - User can get all the attendance records for all the _individuals_ using this option
- **Get Present Subscriber based on Date** (POST Get Present Subscriber based on Date)
  - Using this options user can filter the list of Attendees in a specific date range

**Odoo UI**
- **Attendance Subscriber** - This is a view created under **Attendance** menu on the home page of Odoo UI. User can see the list of **Attendees** fetched via _API1_. 
  - User can add new _Individual / Person / Beneficiaries_ manually on this view. 
  - User Roles
    - Attendance Manager - This user can Create / View / Edit / Delete
    - Attendance Viewer - This user can only View
- **Attendance Details** - This is a view created inside of **Attendee**.
  -  User can see the list of **all** the **Attendance Records** of the **Attendee** fetched via _API2_ under **Attendance** tab.
  - User Roles
    - Attendance Manager - This user can Create / View / Edit / Delete
    - Attendance Viewer - This user can only View

**Comment by lyn88** [comment]
Test environment: Attendance Server 
Browser: Chrome version:129.0.6668.100 (Official Build) (arm64)
OS: MacOS Sonoma 14.3 


**Testing Steps:**
1. Install attendance module to Odoo UI 
-verified that "Attendance" menu is available 
![Screenshot 2024-10-17 at 3 49 54 PM](https://github.com/user-attachments/assets/a7e207b4-e1bc-407b-8648-83ac54a04ece)
2. Configure "Attendance API client credentials" 
-verified that API Client and API Secret UUIDs are prefixed 
Note: "Show" button for API client and secret only appears once so make sure to copy keys on a notepad.

3. Use postman to simulate API 
a.Access Token (POST Get Access Token)
-verified that got response 200
![Screenshot 2024-10-17 at 4 10 12 PM](https://github.com/user-attachments/assets/6e051fee-a01c-4d3f-b0f1-6b53cfcf91f7)

b.Create Attendance (POST Create Attendance)
-verified that got response 200
![Screenshot 2024-10-17 at 4 32 26 PM](https://github.com/user-attachments/assets/d4e48ab7-c231-487f-962f-16fccfff7207)
-verified that attendance declaration reflects on Odoo UI
![Screenshot 2024-10-17 at 4 33 43 PM](https://github.com/user-attachments/assets/e6729ef1-ef7a-435e-b736-32b0d6c29b9e)

c.Get Attendance of all person (POST Get Attendance List)
-verified that got response 200
![Screenshot 2024-10-17 at 4 39 19 PM](https://github.com/user-attachments/assets/f3dcc16b-7670-427c-9b89-700fdc5ac85b)
d.Get Attendance of person (POST Get Person Attendance)
-verified that got response 200
![Screenshot 2024-10-17 at 5 09 05 PM](https://github.com/user-attachments/assets/a8351f0c-8b2b-4e6a-83d3-2fb7aade882b)

e.Get Attendance Types 
-verified that got response 200
![Screenshot 2024-10-17 at 5 21 01 PM](https://github.com/user-attachments/assets/eb10b9d6-43da-4e00-acb1-c84543f7dc4c)

f.Get Attendance Location
-verified that got response 200
![Screenshot 2024-10-17 at 5 21 09 PM](https://github.com/user-attachments/assets/550383cd-4aff-477a-8a77-9d99c64e20c0)

4. Also tested filters on "Get Attendance of person" and "Get Attendance of all person"
-attendance_type
-location_type

4. Sent Attendance declaration via Self-registration app
-verified that attendance declared successfully reflected on the attendance server

**Conclusion:** 
Testing was **successful**. The new attendance module feature is working as expected.
