### ISSUE TITLE
Runboat does not support queues

### ISSUE THREAD

**Issue by kneckinator** [openspp-project/openspp-registry#622]
**Describe the bug**
Not possible to use queues with the runboat instances.

**To Reproduce**

1. Install the "OpenSPP ID Queue" addon, which is using the "queue_job" component.
2. Create an operation that requires the queue to process it.
>Example:
 Import CSV with 1k registrants
Go to Registry >> Groups >> Import records

3. Open the "Job Queue" app and verify that the jobs are not being processed.

**Expected behavior**
Jobs put on the queue should be processed.

**Comment by kneckinator** [comment]
Related to and unblocks #534

**Comment by kneckinator** [comment]
Status update: Made progress, in that queues are installed and started automatically with the runboat process. The Odoo log shows the queues are running in what seems like a proper way.
However, the OpenSPP queues are not working.

I'll investigate further today.

**Comment by kneckinator** [comment]
Last investigation showed that all runboat instances end up subscribing to **all** currently available databases. My **hunch** is that another instance is picking up the notification and as all instances subscribe to all databases, the notifications end up silenced.

I have tried using various parameters that the oca_queue code should care about, however, the code to sniff out all databases is still executed:

```
Apply Request._get_session_and_dbname monkey patch to capture db"
        " from request with multiple databases"
```

The code is here: https://github.com/OCA/queue/blob/17.0/queue_job/post_load.py
If you take a look at the runboat logs of an instance, you will see this output about and you can observe that it is subscribing to all available databases.

My hunch would also explain why, initially, the queue worked as there was only one instance where it was enabled.

**Comment by celinenilla** [comment]
Leaving this for now. We will have to use the other instances to test tickets related to job queues. Placing this in the backlog for possible later fixing.

**Comment by kneckinator** [comment]
The solution was found yesterday and has been tested on Runboat. The solution was to specify the instance database "directly" instead of relying on the parameter `--dbfilter ...` to find it.

The OCA `queue_job` module was incompatible with the odoo-bin parameter `--db-filter` to select a database, even if a single database was returned. I believe this has to do with the fact that this is triggering the database manager, but it seems in the `queue_job` case, the specified filter was not applied and thus all available databases were returned.

Related to this, a similar issue surfaced with the VCI API when `db-filter` was used. In this case, no database was selected. I would have expected that the API would use the same, single, database that the running Odoo instance was using but this was not the case.
