### ISSUE TITLE
DCI API Server Improvements

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#623]
Improve the DCI API Server with the following
- "total_count" is not working. remove it.
- Add pagination.

**Comment by lyn88** [comment]
Test environment: Postman Version 11.2.0
Browser: Chrome Version 130.0.6723.59 (Official Build) (arm64)
OS: MacOS Sonoma 14.3

**Pre-requisites**: load postman collection for this test 

**Testing Steps**:
1. Call _registry/sync/search_ api 
-verified that "total_count" in the header body is removed 
-verified that pagination is added to the response 
![Screenshot 2024-11-07 at 2 46 00 PM](https://github.com/user-attachments/assets/fddf1438-ffee-4967-abd7-4af0002bcb8c)

**Conclusion:**
Testing was successful. Total count on the header body is removed and new pagination added works as expected.
