### ISSUE TITLE
Add a way to prevent conflicting modules to be activated

### ISSUE THREAD

**Issue by celinenilla** [openspp-project/openspp-registry#634]
Conflicting modules, such as **spp_base (SP-MIS)** and **spp_farmer_base (Farmer Registry)**, can be activated by the admin user via the Odoo "Apps" UI. This could lead to errors due to conflicts between the modules. To prevent these issues, a **pre_init_hook** should be implemented in each conflicting module. The hook will contain a function that checks for the presence of the other conflicting module and prevents activation if it's already installed.

An alternative for this is to use "excludes" in __manifest__.py.

**Comment by celinenilla** [comment]
@kneckinator , can you please help advise on which of the two alternatives above we should pick?

**Comment by kneckinator** [comment]
@gonzalesedwin1123 suggested we try the `excludes` section in the manifest first, then explore the `pre_init_hook` if `excludes` does not give us the expected results. I agree with that suggestion.

**Comment by gonzalesedwin1123** [comment]
@kneckinator @celinenilla after trying the `excludes` section in the manifest, I discovered that it is doing what is needed.

**Comment by gonzalesedwin1123** [comment]
I have completed this. Installing conflicting modules will display this:
![Image](https://github.com/user-attachments/assets/e00ca5fd-066d-4845-bbb7-cd75dbacc969)

**Comment by jannahadlaon** [comment]
Findings: Return to devs - testing Blocked
Installing the modules below raised errors
`spp_change_request_add_children_demo`
`spp_change_request_add_farmer`

**STEPS**:
1.
 Install `spp_base` then install `spp_farmer_registry_base` - **PASS**
Error message should popup
![image](https://github.com/user-attachments/assets/71a7a76b-38d9-49d2-9814-75c9e98ea894)

 Install `spp_farmer_registry_base` then install `spp_base`  - **PASS**
![image](https://github.com/user-attachments/assets/d5a3b9c5-2ae4-438d-b206-4173dbc19db1)

2. 
Install `spp_change_request_add_children_demo`  then install `spp_farmer_registry_base` - **FAIL**
Error occurred when installing  `spp_change_request_add_children_demo`
![image](https://github.com/user-attachments/assets/2a2de80d-c1b2-492f-9482-e16c777136ea)

Install `spp_farmer_registry_base`  then install `spp_change_request_add_children_demo` - **PASS**
![image](https://github.com/user-attachments/assets/948eff84-018d-426d-b087-017f8ac02eb8)


3. Installing `spp_change_request_add_farmer` conflicts with `spp_base` - **FAIL**
Error occurred when installing  `spp_change_request_add_farmer`
![image](https://github.com/user-attachments/assets/8ad59dec-f437-43e0-90b5-d33dffd524e6)

Installing  `spp_base`  conflicts with `spp_change_request_add_farmer`  - **PASS**
![image](https://github.com/user-attachments/assets/ebd2d603-ae29-4270-99c1-90f9b3bf92dd)


4. Installing `spp_farmer_registry_default_ui` conflicts with `spp_base` - **PASS**
![image](https://github.com/user-attachments/assets/20bfbc7d-28c7-44db-b035-e0946f7b119c)
Installing `spp_base`  conflicts with  `spp_farmer_registry_default_ui`- **PASS**
![image](https://github.com/user-attachments/assets/9dd10915-8da2-4ec2-8ad4-b678ea3dc4ff)


5. Installing `spp_farmer_registry_demo` conflicts with `spp_base` - **PASS**
![image](https://github.com/user-attachments/assets/d0e9cd57-4c96-4267-8a20-f50938fbe904)

Installing `spp_base` conflicts with `spp_base`  `spp_farmer_registry_demo`- **PASS**
![image](https://github.com/user-attachments/assets/90be7f7d-77ab-4614-a8d5-ef01299b7fe9)

@gonzalesedwin1123 @emjay0921

**Comment by gonzalesedwin1123** [comment]
@jannahadlaon please check again. Thanks.

**Comment by jannahadlaon** [comment]
Findings: **Return to devs - testing Blocked**

1. Install spp_change_request_add_children_demo then install spp_farmer_registry_base - **PASS**
![image](https://github.com/user-attachments/assets/22c00348-59ad-4da4-adb2-edc83ede317a)

2. Installing spp_change_request_add_farmer conflicts with spp_base - **FAIL**
Error occurred when installing spp_change_request_add_farmer
![image](https://github.com/user-attachments/assets/4801f641-57fd-43d9-b60f-6320fe8df918)

CC: @gonzalesedwin1123 @emjay0921

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**

1. Installing spp_change_request_add_farmer conflicts with spp_base - **PASSED**
 ![image](https://github.com/user-attachments/assets/bdfcf6b1-f337-40eb-ad67-1af15e39a0c9)
