### ISSUE TITLE
Access error when logging in as global program manager

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#646]
**Describe the bug**
On an SPMIS configuration instance in runboat, logging in as global program manager displays an access error. although this access error can be dismissed by clicking outside the modal. and only global program manager currently can replicate it.

Instance: http://openspp-openspp-modules-penn-585-1f2ad70d5513.runboatk8.newlogic-demo.com/web/login
Account used: Select "globalprogmanager" from autofill options available in 1pass. 

**To Reproduce**
On the provided instance. login as globalprogram manager.
Upon login , an access error appears.
if no access error appears, try refreshing the page.

**Expected behavior**
Should not display access errors for ANY role upon login

**Screenshots**
![Image](https://github.com/user-attachments/assets/d100a305-5eaf-4b94-85c9-5b8312690642)
![Image](https://github.com/user-attachments/assets/7d256256-0396-4fb8-8a08-816c919a352b)
![Image](https://github.com/user-attachments/assets/3d09a8b8-11a4-45ca-81a8-d0f249b4b8f1)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**

**STEPS**:
1. Create Global Program manager using Admin
2. Log out as admin and log in as global program manager.
3. Verify that global PM user logs in successfully.
