### ISSUE TITLE
Multiplier cannot be accessed by program manager

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#647]
**Describe the bug**
As Global program manager, accessing multiplier dropdown from entitlement manager for either CASH or IN-KIND will display an access error

**To Reproduce**

1. Login to runboat instance: http://openspp-openspp-modules-penn-585-1f2ad70d5513.runboatk8.newlogic-demo.com/web/login using the globalprogmanager available usiing 1pass
2. Go to programs and create a program
3. While creating a program go to "Configure entitlement manager" and select either cash or in-kind 
4. Click on add a line
5. Notice when clicking dropdown for multiplier, it displays an access error

**Expected behavior**
Program manager role should be able to access multiplier dropdown field to be able to configure it
**Screenshots**
![Image](https://github.com/user-attachments/assets/6053bafb-3e42-466f-bdfd-3ae919d5fb7c)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**

**STEPS**:

1. Create Global Program manager using Admin
2. Log out as admin and log in as global program manager. Verify that global PM user logs in successfully.
3. Go to programs and create a program
4. While creating a program go to "Configure entitlement manager" and select either cash or in-kind
5. Click on add a line
6. Verify that you are able to access multiplier and configure it.
https://drive.google.com/file/d/1hXPSzqL0u9ifSmtC9hDEkemYQ4Pc_F3c/view?usp=sharing
