### ISSUE TITLE
Improve Area Import

### ISSUE THREAD

**Issue by reichie020212** [openspp-project/openspp-registry#652]
Importing of area is not working if the xlsx file have 40k+ records. fix this.

**Comment by reichie020212** [comment]
[phl_adminboundaries_tabulardata.xlsx](https://github.com/user-attachments/files/17565192/phl_adminboundaries_tabulardata.xlsx)

**Comment by lyn88** [comment]
**Test environment:** qa-ph
**Browser:** Chrome Version 130.0.6723.59 (Official Build) (arm64)
**OS:** MacOS Sonoma 14.3

**Steps:** 
1. Went to Areas > Areas > Area Import
2. Click New
3. Filled in fields and uploaded file 
![Screenshot 2024-11-07 at 4 47 10 PM](https://github.com/user-attachments/assets/f537a09e-ac11-4651-8d4e-eb1b8f63d9a2)
4. Clicked Import 
-verified that no error on the file was detected out of 43,796
![Screenshot 2024-11-07 at 4 51 54 PM](https://github.com/user-attachments/assets/1b69950a-560a-4e5a-b527-3f4963aba357)
5. Click Validate Data 
-verified that data was validated successfully and that theres no error
![Screenshot 2024-11-07 at 4 55 11 PM](https://github.com/user-attachments/assets/23abf5e0-272b-43f9-9c95-d0c2eaf2083e)
6. Click Save to Area 
-verified that all 43,796 areas has been saved successfully 
![Screenshot 2024-11-07 at 5 20 06 PM](https://github.com/user-attachments/assets/4527eeba-367f-4005-8119-5d1177898c13)


**Conclusion:**
Testing was successful. Area import feature can now handle large data import and works as expected.
