### ISSUE TITLE
Fix SPP Starter for demo modules

### ISSUE THREAD

**Issue by emjay0921** [openspp-project/openspp-registry#660]
Fix errors found when installing with `spp_starter` regarding demo modules (specifically `spp_demo` since it was changed to `spp_mis_demo`). Check other modules as well specially modules that are recently renamed.

**Comment by jannahadlaon** [comment]
Findings: **QA PASSED**

**STEPS**

1. On newly set instance or runboat install spp_starter.
2. Proceed with the setup. (Try with SP-MIS and Farmer Registry, also make sure to test this as demo)
Verified that setup with SP-MIS and Farmer Registry are successful.
