### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#689]
**Describe the bug**
Odoo error appearing when attempting to upload a sample excel file

**To Reproduce**
Login as admin
Go to Registry>Configuration>import
Upload file

Notice an odoo errpr will appear upon upload.

**Expected behavior**
Should be able to upload successfully without issues

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by emjay0921** [comment]
@anthonymarkQA try using this excel file: 
[IMPORT.xlsx](https://github.com/user-attachments/files/18090571/IMPORT.xlsx)

As the attached excel file you used has password, which causes the error.

**Comment by anthonymarkQA** [comment]
Findings: QA Passed

able to import Excel file.
Note this is only tested in QA instance
file used: 
[IMPORT.xlsx](https://github.com/user-attachments/files/18091027/IMPORT.xlsx)
