### ISSUE TITLE
Import photos of beneficiaries

### ISSUE THREAD

**Issue by anthonymarkQA** [openspp-project/openspp-registry#691]
**Describe the bug**
With the use of Openspp import. allow photos to be imported into openspp beneficiaries

**To Reproduce**

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/211b35d1-908b-483a-be23-ccbe6dd266e0)

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

**Comment by singhkaranvir25** [comment]
Photos can be imported by using APIs. Closing this ticket as "Won't do" as its not needed as of now.
