### ISSUE TITLE
Issue translating Area

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-registry#70]
When there is no translation, we should default to the default area name

In English:

![Image](https://user-images.githubusercontent.com/9537/198975082-f06ca7c7-9879-42c5-ae2a-cc3686892649.png)

When switching to French:

![Image](https://user-images.githubusercontent.com/9537/198975139-15a21c75-e3ae-45a3-ac8d-e637d13df50f.png)

**Comment by emjay0921** [comment]
Upon multiple test with different Excel Files on Importing (Also activated multiple Languages). This doesn't need work or fix. It is working as expected now.
